# ``ib_async`` build / dev targets.
#
# Protobuf bindings under ``ib_async/_pb/`` are generated artifacts.
# They are gitignored and regenerated by ``scripts/generate_protos.py``.
# Local dev runs ``make protos`` once after ``uv sync``; release runs
# ``make release`` which regenerates them before building the wheel
# and source distribution so end users get the bindings bundled into
# the package without needing ``protoc`` or ``grpcio-tools``.

.PHONY: help sync protos audit build release publish test lint format clean

PYTHON ?= uv run python
PB_DIR := ib_async/_pb

help:
	@echo "Targets:"
	@echo "  sync     - uv sync --all-groups (install deps + dev extras)"
	@echo "  protos   - fetch+extract TWS API archive (if needed), regenerate $(PB_DIR)/"
	@echo "  audit    - run proto-parity audit vs version-locked client_utils.py"
	@echo "  build    - regenerate protos, then build sdist + wheel into dist/"
	@echo "  release  - full pipeline: fetch + protos + lint + audit + test + build + smoke"
	@echo "  publish  - release pipeline then upload via uv publish"
	@echo "  test     - run the owned test suite"
	@echo "  lint     - ruff check + mypy"
	@echo "  format   - ruff format"
	@echo "  clean    - remove dist/, build/, $(PB_DIR)/, caches"

sync:
	uv sync --all-groups

# Version + SHA256 of the TWS API archive are pinned in pyproject.toml
# under [tool.ib_async.twsapi]. The script handles fetch / cache /
# SHA-verify / extract / protoc — no manual setup needed.
protos:
	$(PYTHON) scripts/generate_protos.py

audit:
	$(PYTHON) scripts/audit_proto_parity.py

# Wheel + sdist always bundle freshly-generated bindings. The
# ``protos`` prerequisite guarantees ``ib_async/_pb/`` exists with
# current schemas before poetry-core scans for ``include`` globs.
build: protos
	uv build

# Full release-engineering pipeline. Aborts before publish on any
# red step (lint / audit / tests / smoke install).
release:
	$(PYTHON) scripts/release.py

publish:
	$(PYTHON) scripts/release.py --publish

test:
	uv run pytest -q

lint:
	uv run python -m ruff check ib_async/ tests/
	uv run python -m mypy ib_async/

format:
	uv run python -m ruff format ib_async/ tests/

clean:
	rm -rf dist/ build/ $(PB_DIR)/ .mypy_cache/ .ruff_cache/
	find . -type d -name __pycache__ -exec rm -rf {} +
