# ``ib_async`` build / dev targets.
#
# Protobuf bindings under ``ib_async/_pb/`` are generated artifacts.
# They are gitignored and regenerated by ``scripts/generate_protos.py``.
# Local dev runs ``make protos`` once after ``uv sync``; release runs
# ``make release`` which regenerates them before building the wheel
# and source distribution so end users get the bindings bundled into
# the package without needing ``protoc`` or ``grpcio-tools``.

.PHONY: help sync protos build release test lint format clean

PYTHON ?= uv run python
PB_DIR := ib_async/_pb

help:
	@echo "Targets:"
	@echo "  sync     - uv sync --all-groups (install deps + dev extras)"
	@echo "  protos   - regenerate ib_async/_pb/ from upstream .proto schemas"
	@echo "  build    - regenerate protos, then build sdist + wheel into dist/"
	@echo "  release  - alias for build (guarantees fresh protos in the artifact)"
	@echo "  test     - run the owned test suite"
	@echo "  lint     - ruff check + mypy"
	@echo "  format   - ruff format"
	@echo "  clean    - remove dist/, build/, generated _pb/, caches"

sync:
	uv sync --all-groups

protos:
	$(PYTHON) scripts/generate_protos.py

# Wheel + sdist always bundle freshly-generated bindings. The
# ``protos`` prerequisite guarantees ``ib_async/_pb/`` exists with
# current schemas before poetry-core scans for ``include`` globs.
build: protos
	uv build

release: build

test:
	uv run pytest -q

lint:
	uv run python -m ruff check ib_async/ tests/
	uv run python -m mypy ib_async/

format:
	uv run python -m ruff format ib_async/ tests/

clean:
	rm -rf dist/ build/ $(PB_DIR)/ .mypy_cache/ .ruff_cache/
	find . -type d -name __pycache__ -exec rm -rf {} +
