# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AccountValue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AccountValue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x41\x63\x63ountValue.proto\x12\x08protobuf\"\x94\x01\n\x0c\x41\x63\x63ountValue\x12\x10\n\x03key\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08\x63urrency\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0b\x61\x63\x63ountName\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x06\n\x04_keyB\x08\n\x06_valueB\x0b\n\t_currencyB\x0e\n\x0c_accountNameB<\n\x16\x63om.ib.client.protobufB\x11\x41\x63\x63ountValueProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AccountValue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\021AccountValueProto\252\002\016IBApi.protobuf'
  _globals['_ACCOUNTVALUE']._serialized_start=33
  _globals['_ACCOUNTVALUE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
