# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AccountUpdatesMultiRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AccountUpdatesMultiRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n AccountUpdatesMultiRequest.proto\x12\x08protobuf\"\xae\x01\n\x1a\x41\x63\x63ountUpdatesMultiRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x14\n\x07\x61\x63\x63ount\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tmodelCode\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x19\n\x0cledgerAndNLV\x18\x04 \x01(\x08H\x03\x88\x01\x01\x42\x08\n\x06_reqIdB\n\n\x08_accountB\x0c\n\n_modelCodeB\x0f\n\r_ledgerAndNLVBJ\n\x16\x63om.ib.client.protobufB\x1f\x41\x63\x63ountUpdatesMultiRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AccountUpdatesMultiRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\037AccountUpdatesMultiRequestProto\252\002\016IBApi.protobuf'
  _globals['_ACCOUNTUPDATESMULTIREQUEST']._serialized_start=47
  _globals['_ACCOUNTUPDATESMULTIREQUEST']._serialized_end=221
# @@protoc_insertion_point(module_scope)
