# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AccountSummaryRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AccountSummaryRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x41\x63\x63ountSummaryRequest.proto\x12\x08protobuf\"o\n\x15\x41\x63\x63ountSummaryRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05group\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04tags\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x08\n\x06_reqIdB\x08\n\x06_groupB\x07\n\x05_tagsBE\n\x16\x63om.ib.client.protobufB\x1a\x41\x63\x63ountSummaryRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AccountSummaryRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\032AccountSummaryRequestProto\252\002\016IBApi.protobuf'
  _globals['_ACCOUNTSUMMARYREQUEST']._serialized_start=41
  _globals['_ACCOUNTSUMMARYREQUEST']._serialized_end=152
# @@protoc_insertion_point(module_scope)
