# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AccountSummary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AccountSummary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x41\x63\x63ountSummary.proto\x12\x08protobuf\"\xac\x01\n\x0e\x41\x63\x63ountSummary\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x14\n\x07\x61\x63\x63ount\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x03tag\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x12\n\x05value\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08\x63urrency\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\x08\n\x06_reqIdB\n\n\x08_accountB\x06\n\x04_tagB\x08\n\x06_valueB\x0b\n\t_currencyB>\n\x16\x63om.ib.client.protobufB\x13\x41\x63\x63ountSummaryProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AccountSummary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\023AccountSummaryProto\252\002\016IBApi.protobuf'
  _globals['_ACCOUNTSUMMARY']._serialized_start=35
  _globals['_ACCOUNTSUMMARY']._serialized_end=207
# @@protoc_insertion_point(module_scope)
