# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AutoOpenOrdersRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'AutoOpenOrdersRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x41utoOpenOrdersRequest.proto\x12\x08protobuf\";\n\x15\x41utoOpenOrdersRequest\x12\x15\n\x08\x61utoBind\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x0b\n\t_autoBindBE\n\x16\x63om.ib.client.protobufB\x1a\x41utoOpenOrdersRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AutoOpenOrdersRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\032AutoOpenOrdersRequestProto\252\002\016IBApi.protobuf'
  _globals['_AUTOOPENORDERSREQUEST']._serialized_start=41
  _globals['_AUTOOPENORDERSREQUEST']._serialized_end=100
# @@protoc_insertion_point(module_scope)
