# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CalculateImpliedVolatilityRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CalculateImpliedVolatilityRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Contract_pb2 as Contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'CalculateImpliedVolatilityRequest.proto\x12\x08protobuf\x1a\x0e\x43ontract.proto\"\xf9\x02\n!CalculateImpliedVolatilityRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12)\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x12.protobuf.ContractH\x01\x88\x01\x01\x12\x18\n\x0boptionPrice\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x17\n\nunderPrice\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12k\n\x18impliedVolatilityOptions\x18\x05 \x03(\x0b\x32I.protobuf.CalculateImpliedVolatilityRequest.ImpliedVolatilityOptionsEntry\x1a?\n\x1dImpliedVolatilityOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_reqIdB\x0b\n\t_contractB\x0e\n\x0c_optionPriceB\r\n\x0b_underPriceBQ\n\x16\x63om.ib.client.protobufB&CalculateImpliedVolatilityRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CalculateImpliedVolatilityRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB&CalculateImpliedVolatilityRequestProto\252\002\016IBApi.protobuf'
  _globals['_CALCULATEIMPLIEDVOLATILITYREQUEST_IMPLIEDVOLATILITYOPTIONSENTRY']._loaded_options = None
  _globals['_CALCULATEIMPLIEDVOLATILITYREQUEST_IMPLIEDVOLATILITYOPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_CALCULATEIMPLIEDVOLATILITYREQUEST']._serialized_start=70
  _globals['_CALCULATEIMPLIEDVOLATILITYREQUEST']._serialized_end=447
  _globals['_CALCULATEIMPLIEDVOLATILITYREQUEST_IMPLIEDVOLATILITYOPTIONSENTRY']._serialized_start=330
  _globals['_CALCULATEIMPLIEDVOLATILITYREQUEST_IMPLIEDVOLATILITYOPTIONSENTRY']._serialized_end=393
# @@protoc_insertion_point(module_scope)
