# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CancelOrderRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CancelOrderRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import OrderCancel_pb2 as OrderCancel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43\x61ncelOrderRequest.proto\x12\x08protobuf\x1a\x11OrderCancel.proto\"w\n\x12\x43\x61ncelOrderRequest\x12\x14\n\x07orderId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12/\n\x0borderCancel\x18\x02 \x01(\x0b\x32\x15.protobuf.OrderCancelH\x01\x88\x01\x01\x42\n\n\x08_orderIdB\x0e\n\x0c_orderCancelBB\n\x16\x63om.ib.client.protobufB\x17\x43\x61ncelOrderRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CancelOrderRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\027CancelOrderRequestProto\252\002\016IBApi.protobuf'
  _globals['_CANCELORDERREQUEST']._serialized_start=57
  _globals['_CANCELORDERREQUEST']._serialized_end=176
# @@protoc_insertion_point(module_scope)
