# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CommissionAndFeesReport.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CommissionAndFeesReport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x43ommissionAndFeesReport.proto\x12\x08protobuf\"\x9d\x02\n\x17\x43ommissionAndFeesReport\x12\x13\n\x06\x65xecId\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1e\n\x11\x63ommissionAndFees\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x15\n\x08\x63urrency\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0brealizedPNL\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12\x16\n\tbondYield\x18\x05 \x01(\x01H\x04\x88\x01\x01\x12 \n\x13yieldRedemptionDate\x18\x06 \x01(\tH\x05\x88\x01\x01\x42\t\n\x07_execIdB\x14\n\x12_commissionAndFeesB\x0b\n\t_currencyB\x0e\n\x0c_realizedPNLB\x0c\n\n_bondYieldB\x16\n\x14_yieldRedemptionDateBG\n\x16\x63om.ib.client.protobufB\x1c\x43ommissionAndFeesReportProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommissionAndFeesReport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\034CommissionAndFeesReportProto\252\002\016IBApi.protobuf'
  _globals['_COMMISSIONANDFEESREPORT']._serialized_start=44
  _globals['_COMMISSIONANDFEESREPORT']._serialized_end=329
# @@protoc_insertion_point(module_scope)
