# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CurrentTimeInMillis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CurrentTimeInMillis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x43urrentTimeInMillis.proto\x12\x08protobuf\"O\n\x13\x43urrentTimeInMillis\x12 \n\x13\x63urrentTimeInMillis\x18\x01 \x01(\x03H\x00\x88\x01\x01\x42\x16\n\x14_currentTimeInMillisBC\n\x16\x63om.ib.client.protobufB\x18\x43urrentTimeInMillisProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CurrentTimeInMillis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\030CurrentTimeInMillisProto\252\002\016IBApi.protobuf'
  _globals['_CURRENTTIMEINMILLIS']._serialized_start=39
  _globals['_CURRENTTIMEINMILLIS']._serialized_end=118
# @@protoc_insertion_point(module_scope)
