# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DepthMarketDataDescription.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DepthMarketDataDescription.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n DepthMarketDataDescription.proto\x12\x08protobuf\"\xe2\x01\n\x1a\x44\x65pthMarketDataDescription\x12\x15\n\x08\x65xchange\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07secType\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0blistingExch\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1c\n\x0fserviceDataType\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08\x61ggGroup\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\x0b\n\t_exchangeB\n\n\x08_secTypeB\x0e\n\x0c_listingExchB\x12\n\x10_serviceDataTypeB\x0b\n\t_aggGroupBJ\n\x16\x63om.ib.client.protobufB\x1f\x44\x65pthMarketDataDescriptionProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DepthMarketDataDescription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\037DepthMarketDataDescriptionProto\252\002\016IBApi.protobuf'
  _globals['_DEPTHMARKETDATADESCRIPTION']._serialized_start=47
  _globals['_DEPTHMARKETDATADESCRIPTION']._serialized_end=273
# @@protoc_insertion_point(module_scope)
