# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ExerciseOptionsRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ExerciseOptionsRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Contract_pb2 as Contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x45xerciseOptionsRequest.proto\x12\x08protobuf\x1a\x0e\x43ontract.proto\"\xbc\x03\n\x16\x45xerciseOptionsRequest\x12\x14\n\x07orderId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12)\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x12.protobuf.ContractH\x01\x88\x01\x01\x12\x1b\n\x0e\x65xerciseAction\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x1d\n\x10\x65xerciseQuantity\x18\x04 \x01(\x05H\x03\x88\x01\x01\x12\x14\n\x07\x61\x63\x63ount\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x15\n\x08override\x18\x06 \x01(\x08H\x05\x88\x01\x01\x12\x1c\n\x0fmanualOrderTime\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x1c\n\x0f\x63ustomerAccount\x18\x08 \x01(\tH\x07\x88\x01\x01\x12!\n\x14professionalCustomer\x18\t \x01(\x08H\x08\x88\x01\x01\x42\n\n\x08_orderIdB\x0b\n\t_contractB\x11\n\x0f_exerciseActionB\x13\n\x11_exerciseQuantityB\n\n\x08_accountB\x0b\n\t_overrideB\x12\n\x10_manualOrderTimeB\x12\n\x10_customerAccountB\x17\n\x15_professionalCustomerBF\n\x16\x63om.ib.client.protobufB\x1b\x45xerciseOptionsRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExerciseOptionsRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\033ExerciseOptionsRequestProto\252\002\016IBApi.protobuf'
  _globals['_EXERCISEOPTIONSREQUEST']._serialized_start=59
  _globals['_EXERCISEOPTIONSREQUEST']._serialized_end=503
# @@protoc_insertion_point(module_scope)
