# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FamilyCodes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FamilyCodes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import FamilyCode_pb2 as FamilyCode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x46\x61milyCodes.proto\x12\x08protobuf\x1a\x10\x46\x61milyCode.proto\"8\n\x0b\x46\x61milyCodes\x12)\n\x0b\x66\x61milyCodes\x18\x01 \x03(\x0b\x32\x14.protobuf.FamilyCodeB;\n\x16\x63om.ib.client.protobufB\x10\x46\x61milyCodesProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FamilyCodes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\020FamilyCodesProto\252\002\016IBApi.protobuf'
  _globals['_FAMILYCODES']._serialized_start=49
  _globals['_FAMILYCODES']._serialized_end=105
# @@protoc_insertion_point(module_scope)
