# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FundamentalsDataRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'FundamentalsDataRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Contract_pb2 as Contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x46undamentalsDataRequest.proto\x12\x08protobuf\x1a\x0e\x43ontract.proto\"\xb8\x02\n\x17\x46undamentalsDataRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12)\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x12.protobuf.ContractH\x01\x88\x01\x01\x12\x17\n\nreportType\x18\x03 \x01(\tH\x02\x88\x01\x01\x12_\n\x17\x66undamentalsDataOptions\x18\x04 \x03(\x0b\x32>.protobuf.FundamentalsDataRequest.FundamentalsDataOptionsEntry\x1a>\n\x1c\x46undamentalsDataOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_reqIdB\x0b\n\t_contractB\r\n\x0b_reportTypeBG\n\x16\x63om.ib.client.protobufB\x1c\x46undamentalsDataRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FundamentalsDataRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\034FundamentalsDataRequestProto\252\002\016IBApi.protobuf'
  _globals['_FUNDAMENTALSDATAREQUEST_FUNDAMENTALSDATAOPTIONSENTRY']._loaded_options = None
  _globals['_FUNDAMENTALSDATAREQUEST_FUNDAMENTALSDATAOPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_FUNDAMENTALSDATAREQUEST']._serialized_start=60
  _globals['_FUNDAMENTALSDATAREQUEST']._serialized_end=372
  _globals['_FUNDAMENTALSDATAREQUEST_FUNDAMENTALSDATAOPTIONSENTRY']._serialized_start=272
  _globals['_FUNDAMENTALSDATAREQUEST_FUNDAMENTALSDATAOPTIONSENTRY']._serialized_end=334
# @@protoc_insertion_point(module_scope)
