# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HeadTimestampRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HeadTimestampRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Contract_pb2 as Contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aHeadTimestampRequest.proto\x12\x08protobuf\x1a\x0e\x43ontract.proto\"\xdc\x01\n\x14HeadTimestampRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12)\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x12.protobuf.ContractH\x01\x88\x01\x01\x12\x13\n\x06useRTH\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12\x17\n\nwhatToShow\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x17\n\nformatDate\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\x08\n\x06_reqIdB\x0b\n\t_contractB\t\n\x07_useRTHB\r\n\x0b_whatToShowB\r\n\x0b_formatDateBD\n\x16\x63om.ib.client.protobufB\x19HeadTimestampRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HeadTimestampRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\031HeadTimestampRequestProto\252\002\016IBApi.protobuf'
  _globals['_HEADTIMESTAMPREQUEST']._serialized_start=57
  _globals['_HEADTIMESTAMPREQUEST']._serialized_end=277
# @@protoc_insertion_point(module_scope)
