# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HistoricalNews.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HistoricalNews.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14HistoricalNews.proto\x12\x08protobuf\"\xc0\x01\n\x0eHistoricalNews\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04time\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x19\n\x0cproviderCode\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\tarticleId\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08headline\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\x08\n\x06_reqIdB\x07\n\x05_timeB\x0f\n\r_providerCodeB\x0c\n\n_articleIdB\x0b\n\t_headlineB>\n\x16\x63om.ib.client.protobufB\x13HistoricalNewsProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HistoricalNews_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\023HistoricalNewsProto\252\002\016IBApi.protobuf'
  _globals['_HISTORICALNEWS']._serialized_start=35
  _globals['_HISTORICALNEWS']._serialized_end=227
# @@protoc_insertion_point(module_scope)
