# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HistoricalNewsRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HistoricalNewsRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bHistoricalNewsRequest.proto\x12\x08protobuf\"\x9e\x03\n\x15HistoricalNewsRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05\x63onId\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x1a\n\rproviderCodes\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1a\n\rstartDateTime\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0b\x65ndDateTime\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x19\n\x0ctotalResults\x18\x06 \x01(\x05H\x05\x88\x01\x01\x12Y\n\x15historicalNewsOptions\x18\x07 \x03(\x0b\x32:.protobuf.HistoricalNewsRequest.HistoricalNewsOptionsEntry\x1a<\n\x1aHistoricalNewsOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_reqIdB\x08\n\x06_conIdB\x10\n\x0e_providerCodesB\x10\n\x0e_startDateTimeB\x0e\n\x0c_endDateTimeB\x0f\n\r_totalResultsBE\n\x16\x63om.ib.client.protobufB\x1aHistoricalNewsRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HistoricalNewsRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\032HistoricalNewsRequestProto\252\002\016IBApi.protobuf'
  _globals['_HISTORICALNEWSREQUEST_HISTORICALNEWSOPTIONSENTRY']._loaded_options = None
  _globals['_HISTORICALNEWSREQUEST_HISTORICALNEWSOPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_HISTORICALNEWSREQUEST']._serialized_start=42
  _globals['_HISTORICALNEWSREQUEST']._serialized_end=456
  _globals['_HISTORICALNEWSREQUEST_HISTORICALNEWSOPTIONSENTRY']._serialized_start=307
  _globals['_HISTORICALNEWSREQUEST_HISTORICALNEWSOPTIONSENTRY']._serialized_end=367
# @@protoc_insertion_point(module_scope)
