# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HistoricalSession.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HistoricalSession.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17HistoricalSession.proto\x12\x08protobuf\"\x8d\x01\n\x11HistoricalSession\x12\x1a\n\rstartDateTime\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x65ndDateTime\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07refDate\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x10\n\x0e_startDateTimeB\x0e\n\x0c_endDateTimeB\n\n\x08_refDateBA\n\x16\x63om.ib.client.protobufB\x16HistoricalSessionProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HistoricalSession_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\026HistoricalSessionProto\252\002\016IBApi.protobuf'
  _globals['_HISTORICALSESSION']._serialized_start=38
  _globals['_HISTORICALSESSION']._serialized_end=179
# @@protoc_insertion_point(module_scope)
