# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HistoricalTickBidAsk.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HistoricalTickBidAsk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import TickAttribBidAsk_pb2 as TickAttribBidAsk__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aHistoricalTickBidAsk.proto\x12\x08protobuf\x1a\x16TickAttribBidAsk.proto\"\x8e\x02\n\x14HistoricalTickBidAsk\x12\x11\n\x04time\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x39\n\x10tickAttribBidAsk\x18\x02 \x01(\x0b\x32\x1a.protobuf.TickAttribBidAskH\x01\x88\x01\x01\x12\x15\n\x08priceBid\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x15\n\x08priceAsk\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12\x14\n\x07sizeBid\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x14\n\x07sizeAsk\x18\x06 \x01(\tH\x05\x88\x01\x01\x42\x07\n\x05_timeB\x13\n\x11_tickAttribBidAskB\x0b\n\t_priceBidB\x0b\n\t_priceAskB\n\n\x08_sizeBidB\n\n\x08_sizeAskBD\n\x16\x63om.ib.client.protobufB\x19HistoricalTickBidAskProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HistoricalTickBidAsk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\031HistoricalTickBidAskProto\252\002\016IBApi.protobuf'
  _globals['_HISTORICALTICKBIDASK']._serialized_start=65
  _globals['_HISTORICALTICKBIDASK']._serialized_end=335
# @@protoc_insertion_point(module_scope)
