# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HistoricalDataRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HistoricalDataRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Contract_pb2 as Contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bHistoricalDataRequest.proto\x12\x08protobuf\x1a\x0e\x43ontract.proto\"\x85\x04\n\x15HistoricalDataRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12)\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x12.protobuf.ContractH\x01\x88\x01\x01\x12\x18\n\x0b\x65ndDateTime\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1b\n\x0e\x62\x61rSizeSetting\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08\x64uration\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x13\n\x06useRTH\x18\x06 \x01(\x08H\x05\x88\x01\x01\x12\x17\n\nwhatToShow\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x17\n\nformatDate\x18\x08 \x01(\x05H\x07\x88\x01\x01\x12\x19\n\x0ckeepUpToDate\x18\t \x01(\x08H\x08\x88\x01\x01\x12G\n\x0c\x63hartOptions\x18\n \x03(\x0b\x32\x31.protobuf.HistoricalDataRequest.ChartOptionsEntry\x1a\x33\n\x11\x43hartOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_reqIdB\x0b\n\t_contractB\x0e\n\x0c_endDateTimeB\x11\n\x0f_barSizeSettingB\x0b\n\t_durationB\t\n\x07_useRTHB\r\n\x0b_whatToShowB\r\n\x0b_formatDateB\x0f\n\r_keepUpToDateBE\n\x16\x63om.ib.client.protobufB\x1aHistoricalDataRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HistoricalDataRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\032HistoricalDataRequestProto\252\002\016IBApi.protobuf'
  _globals['_HISTORICALDATAREQUEST_CHARTOPTIONSENTRY']._loaded_options = None
  _globals['_HISTORICALDATAREQUEST_CHARTOPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_HISTORICALDATAREQUEST']._serialized_start=58
  _globals['_HISTORICALDATAREQUEST']._serialized_end=575
  _globals['_HISTORICALDATAREQUEST_CHARTOPTIONSENTRY']._serialized_start=395
  _globals['_HISTORICALDATAREQUEST_CHARTOPTIONSENTRY']._serialized_end=446
# @@protoc_insertion_point(module_scope)
