# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HistoricalSchedule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HistoricalSchedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import HistoricalSession_pb2 as HistoricalSession__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18HistoricalSchedule.proto\x12\x08protobuf\x1a\x17HistoricalSession.proto\"\xe7\x01\n\x12HistoricalSchedule\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x1a\n\rstartDateTime\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x65ndDateTime\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08timeZone\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x37\n\x12historicalSessions\x18\x05 \x03(\x0b\x32\x1b.protobuf.HistoricalSessionB\x08\n\x06_reqIdB\x10\n\x0e_startDateTimeB\x0e\n\x0c_endDateTimeB\x0b\n\t_timeZoneBB\n\x16\x63om.ib.client.protobufB\x17HistoricalScheduleProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HistoricalSchedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\027HistoricalScheduleProto\252\002\016IBApi.protobuf'
  _globals['_HISTORICALSCHEDULE']._serialized_start=64
  _globals['_HISTORICALSCHEDULE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
