# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HistoricalData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HistoricalData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import HistoricalDataBar_pb2 as HistoricalDataBar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14HistoricalData.proto\x12\x08protobuf\x1a\x17HistoricalDataBar.proto\"g\n\x0eHistoricalData\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x37\n\x12historicalDataBars\x18\x02 \x03(\x0b\x32\x1b.protobuf.HistoricalDataBarB\x08\n\x06_reqIdB>\n\x16\x63om.ib.client.protobufB\x13HistoricalDataProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HistoricalData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\023HistoricalDataProto\252\002\016IBApi.protobuf'
  _globals['_HISTORICALDATA']._serialized_start=59
  _globals['_HISTORICALDATA']._serialized_end=162
# @@protoc_insertion_point(module_scope)
