# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HistoricalDataBar.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HistoricalDataBar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17HistoricalDataBar.proto\x12\x08protobuf\"\xfd\x01\n\x11HistoricalDataBar\x12\x11\n\x04\x64\x61te\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04open\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x11\n\x04high\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x10\n\x03low\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12\x12\n\x05\x63lose\x18\x05 \x01(\x01H\x04\x88\x01\x01\x12\x13\n\x06volume\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x10\n\x03WAP\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x15\n\x08\x62\x61rCount\x18\x08 \x01(\x05H\x07\x88\x01\x01\x42\x07\n\x05_dateB\x07\n\x05_openB\x07\n\x05_highB\x06\n\x04_lowB\x08\n\x06_closeB\t\n\x07_volumeB\x06\n\x04_WAPB\x0b\n\t_barCountBA\n\x16\x63om.ib.client.protobufB\x16HistoricalDataBarProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HistoricalDataBar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\026HistoricalDataBarProto\252\002\016IBApi.protobuf'
  _globals['_HISTORICALDATABAR']._serialized_start=38
  _globals['_HISTORICALDATABAR']._serialized_end=291
# @@protoc_insertion_point(module_scope)
