# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HistoricalTickLast.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HistoricalTickLast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import TickAttribLast_pb2 as TickAttribLast__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18HistoricalTickLast.proto\x12\x08protobuf\x1a\x14TickAttribLast.proto\"\x8e\x02\n\x12HistoricalTickLast\x12\x11\n\x04time\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x35\n\x0etickAttribLast\x18\x02 \x01(\x0b\x32\x18.protobuf.TickAttribLastH\x01\x88\x01\x01\x12\x12\n\x05price\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x11\n\x04size\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08\x65xchange\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1e\n\x11specialConditions\x18\x06 \x01(\tH\x05\x88\x01\x01\x42\x07\n\x05_timeB\x11\n\x0f_tickAttribLastB\x08\n\x06_priceB\x07\n\x05_sizeB\x0b\n\t_exchangeB\x14\n\x12_specialConditionsBB\n\x16\x63om.ib.client.protobufB\x17HistoricalTickLastProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HistoricalTickLast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\027HistoricalTickLastProto\252\002\016IBApi.protobuf'
  _globals['_HISTORICALTICKLAST']._serialized_start=61
  _globals['_HISTORICALTICKLAST']._serialized_end=331
# @@protoc_insertion_point(module_scope)
