# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HistoricalTicksBidAsk.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'HistoricalTicksBidAsk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import HistoricalTickBidAsk_pb2 as HistoricalTickBidAsk__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bHistoricalTicksBidAsk.proto\x12\x08protobuf\x1a\x1aHistoricalTickBidAsk.proto\"\x94\x01\n\x15HistoricalTicksBidAsk\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12=\n\x15historicalTicksBidAsk\x18\x02 \x03(\x0b\x32\x1e.protobuf.HistoricalTickBidAsk\x12\x13\n\x06isDone\x18\x03 \x01(\x08H\x01\x88\x01\x01\x42\x08\n\x06_reqIdB\t\n\x07_isDoneBE\n\x16\x63om.ib.client.protobufB\x1aHistoricalTicksBidAskProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HistoricalTicksBidAsk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\032HistoricalTicksBidAskProto\252\002\016IBApi.protobuf'
  _globals['_HISTORICALTICKSBIDASK']._serialized_start=70
  _globals['_HISTORICALTICKSBIDASK']._serialized_end=218
# @@protoc_insertion_point(module_scope)
