# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MarketDepthExchanges.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MarketDepthExchanges.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import DepthMarketDataDescription_pb2 as DepthMarketDataDescription__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aMarketDepthExchanges.proto\x12\x08protobuf\x1a DepthMarketDataDescription.proto\"a\n\x14MarketDepthExchanges\x12I\n\x1b\x64\x65pthMarketDataDescriptions\x18\x01 \x03(\x0b\x32$.protobuf.DepthMarketDataDescriptionBD\n\x16\x63om.ib.client.protobufB\x19MarketDepthExchangesProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MarketDepthExchanges_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\031MarketDepthExchangesProto\252\002\016IBApi.protobuf'
  _globals['_MARKETDEPTHEXCHANGES']._serialized_start=74
  _globals['_MARKETDEPTHEXCHANGES']._serialized_end=171
# @@protoc_insertion_point(module_scope)
