# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MarketDepthData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MarketDepthData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15MarketDepthData.proto\x12\x08protobuf\"\x87\x02\n\x0fMarketDepthData\x12\x15\n\x08position\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\toperation\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x11\n\x04side\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x12\n\x05price\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12\x11\n\x04size\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0bmarketMaker\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x19\n\x0cisSmartDepth\x18\x07 \x01(\x08H\x06\x88\x01\x01\x42\x0b\n\t_positionB\x0c\n\n_operationB\x07\n\x05_sideB\x08\n\x06_priceB\x07\n\x05_sizeB\x0e\n\x0c_marketMakerB\x0f\n\r_isSmartDepthB?\n\x16\x63om.ib.client.protobufB\x14MarketDepthDataProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MarketDepthData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\024MarketDepthDataProto\252\002\016IBApi.protobuf'
  _globals['_MARKETDEPTHDATA']._serialized_start=36
  _globals['_MARKETDEPTHDATA']._serialized_end=299
# @@protoc_insertion_point(module_scope)
