# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MarketDepthRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MarketDepthRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Contract_pb2 as Contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18MarketDepthRequest.proto\x12\x08protobuf\x1a\x0e\x43ontract.proto\"\xc5\x02\n\x12MarketDepthRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12)\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x12.protobuf.ContractH\x01\x88\x01\x01\x12\x14\n\x07numRows\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x19\n\x0cisSmartDepth\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12P\n\x12marketDepthOptions\x18\x05 \x03(\x0b\x32\x34.protobuf.MarketDepthRequest.MarketDepthOptionsEntry\x1a\x39\n\x17MarketDepthOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_reqIdB\x0b\n\t_contractB\n\n\x08_numRowsB\x0f\n\r_isSmartDepthBB\n\x16\x63om.ib.client.protobufB\x17MarketDepthRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MarketDepthRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\027MarketDepthRequestProto\252\002\016IBApi.protobuf'
  _globals['_MARKETDEPTHREQUEST_MARKETDEPTHOPTIONSENTRY']._loaded_options = None
  _globals['_MARKETDEPTHREQUEST_MARKETDEPTHOPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_MARKETDEPTHREQUEST']._serialized_start=55
  _globals['_MARKETDEPTHREQUEST']._serialized_end=380
  _globals['_MARKETDEPTHREQUEST_MARKETDEPTHOPTIONSENTRY']._serialized_start=271
  _globals['_MARKETDEPTHREQUEST_MARKETDEPTHOPTIONSENTRY']._serialized_end=328
# @@protoc_insertion_point(module_scope)
