# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MarketDataRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MarketDataRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Contract_pb2 as Contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17MarketDataRequest.proto\x12\x08protobuf\x1a\x0e\x43ontract.proto\"\x80\x03\n\x11MarketDataRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12)\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x12.protobuf.ContractH\x01\x88\x01\x01\x12\x1c\n\x0fgenericTickList\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08snapshot\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12\x1f\n\x12regulatorySnapshot\x18\x05 \x01(\x08H\x04\x88\x01\x01\x12M\n\x11marketDataOptions\x18\x06 \x03(\x0b\x32\x32.protobuf.MarketDataRequest.MarketDataOptionsEntry\x1a\x38\n\x16MarketDataOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_reqIdB\x0b\n\t_contractB\x12\n\x10_genericTickListB\x0b\n\t_snapshotB\x15\n\x13_regulatorySnapshotBA\n\x16\x63om.ib.client.protobufB\x16MarketDataRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MarketDataRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\026MarketDataRequestProto\252\002\016IBApi.protobuf'
  _globals['_MARKETDATAREQUEST_MARKETDATAOPTIONSENTRY']._loaded_options = None
  _globals['_MARKETDATAREQUEST_MARKETDATAOPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_MARKETDATAREQUEST']._serialized_start=54
  _globals['_MARKETDATAREQUEST']._serialized_end=438
  _globals['_MARKETDATAREQUEST_MARKETDATAOPTIONSENTRY']._serialized_start=303
  _globals['_MARKETDATAREQUEST_MARKETDATAOPTIONSENTRY']._serialized_end=359
# @@protoc_insertion_point(module_scope)
