# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: NewsProviders.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'NewsProviders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import NewsProvider_pb2 as NewsProvider__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13NewsProviders.proto\x12\x08protobuf\x1a\x12NewsProvider.proto\">\n\rNewsProviders\x12-\n\rnewsProviders\x18\x01 \x03(\x0b\x32\x16.protobuf.NewsProviderB=\n\x16\x63om.ib.client.protobufB\x12NewsProvidersProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NewsProviders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\022NewsProvidersProto\252\002\016IBApi.protobuf'
  _globals['_NEWSPROVIDERS']._serialized_start=53
  _globals['_NEWSPROVIDERS']._serialized_end=115
# @@protoc_insertion_point(module_scope)
