# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: NewsBulletin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'NewsBulletin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12NewsBulletin.proto\x12\x08protobuf\"\xba\x01\n\x0cNewsBulletin\x12\x16\n\tnewsMsgId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0bnewsMsgType\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x18\n\x0bnewsMessage\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1c\n\x0foriginatingExch\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x0c\n\n_newsMsgIdB\x0e\n\x0c_newsMsgTypeB\x0e\n\x0c_newsMessageB\x12\n\x10_originatingExchB<\n\x16\x63om.ib.client.protobufB\x11NewsBulletinProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NewsBulletin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\021NewsBulletinProto\252\002\016IBApi.protobuf'
  _globals['_NEWSBULLETIN']._serialized_start=33
  _globals['_NEWSBULLETIN']._serialized_end=219
# @@protoc_insertion_point(module_scope)
