# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: NewsArticleRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'NewsArticleRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18NewsArticleRequest.proto\x12\x08protobuf\"\x91\x02\n\x12NewsArticleRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x19\n\x0cproviderCode\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tarticleId\x18\x03 \x01(\tH\x02\x88\x01\x01\x12P\n\x12newsArticleOptions\x18\x04 \x03(\x0b\x32\x34.protobuf.NewsArticleRequest.NewsArticleOptionsEntry\x1a\x39\n\x17NewsArticleOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_reqIdB\x0f\n\r_providerCodeB\x0c\n\n_articleIdBB\n\x16\x63om.ib.client.protobufB\x17NewsArticleRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NewsArticleRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\027NewsArticleRequestProto\252\002\016IBApi.protobuf'
  _globals['_NEWSARTICLEREQUEST_NEWSARTICLEOPTIONSENTRY']._loaded_options = None
  _globals['_NEWSARTICLEREQUEST_NEWSARTICLEOPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_NEWSARTICLEREQUEST']._serialized_start=39
  _globals['_NEWSARTICLEREQUEST']._serialized_end=312
  _globals['_NEWSARTICLEREQUEST_NEWSARTICLEOPTIONSENTRY']._serialized_start=214
  _globals['_NEWSARTICLEREQUEST_NEWSARTICLEOPTIONSENTRY']._serialized_end=271
# @@protoc_insertion_point(module_scope)
