# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OpenOrder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'OpenOrder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Contract_pb2 as Contract__pb2
from . import Order_pb2 as Order__pb2
from . import OrderState_pb2 as OrderState__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fOpenOrder.proto\x12\x08protobuf\x1a\x0e\x43ontract.proto\x1a\x0bOrder.proto\x1a\x10OrderState.proto\"\xd2\x01\n\tOpenOrder\x12\x14\n\x07orderId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12)\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x12.protobuf.ContractH\x01\x88\x01\x01\x12#\n\x05order\x18\x03 \x01(\x0b\x32\x0f.protobuf.OrderH\x02\x88\x01\x01\x12-\n\norderState\x18\x04 \x01(\x0b\x32\x14.protobuf.OrderStateH\x03\x88\x01\x01\x42\n\n\x08_orderIdB\x0b\n\t_contractB\x08\n\x06_orderB\r\n\x0b_orderStateB9\n\x16\x63om.ib.client.protobufB\x0eOpenOrderProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OpenOrder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\016OpenOrderProto\252\002\016IBApi.protobuf'
  _globals['_OPENORDER']._serialized_start=77
  _globals['_OPENORDER']._serialized_end=287
# @@protoc_insertion_point(module_scope)
