import OrderCondition_pb2 as _OrderCondition_pb2
import SoftDollarTier_pb2 as _SoftDollarTier_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Iterable as _Iterable, Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class Order(_message.Message):
    __slots__ = ("clientId", "orderId", "permId", "parentId", "action", "totalQuantity", "displaySize", "orderType", "lmtPrice", "auxPrice", "tif", "account", "settlingFirm", "clearingAccount", "clearingIntent", "allOrNone", "blockOrder", "hidden", "outsideRth", "sweepToFill", "percentOffset", "trailingPercent", "trailStopPrice", "minQty", "goodAfterTime", "goodTillDate", "ocaGroup", "orderRef", "rule80A", "ocaType", "triggerMethod", "activeStartTime", "activeStopTime", "faGroup", "faMethod", "faPercentage", "volatility", "volatilityType", "continuousUpdate", "referencePriceType", "deltaNeutralOrderType", "deltaNeutralAuxPrice", "deltaNeutralConId", "deltaNeutralOpenClose", "deltaNeutralShortSale", "deltaNeutralShortSaleSlot", "deltaNeutralDesignatedLocation", "scaleInitLevelSize", "scaleSubsLevelSize", "scalePriceIncrement", "scalePriceAdjustValue", "scalePriceAdjustInterval", "scaleProfitOffset", "scaleAutoReset", "scaleInitPosition", "scaleInitFillQty", "scaleRandomPercent", "scaleTable", "hedgeType", "hedgeParam", "algoStrategy", "algoParams", "algoId", "smartComboRoutingParams", "whatIf", "transmit", "overridePercentageConstraints", "openClose", "origin", "shortSaleSlot", "designatedLocation", "exemptCode", "deltaNeutralSettlingFirm", "deltaNeutralClearingAccount", "deltaNeutralClearingIntent", "discretionaryAmt", "optOutSmartRouting", "startingPrice", "stockRefPrice", "delta", "stockRangeLower", "stockRangeUpper", "notHeld", "orderMiscOptions", "solicited", "randomizeSize", "randomizePrice", "referenceContractId", "peggedChangeAmount", "isPeggedChangeAmountDecrease", "referenceChangeAmount", "referenceExchangeId", "adjustedOrderType", "triggerPrice", "adjustedStopPrice", "adjustedStopLimitPrice", "adjustedTrailingAmount", "adjustableTrailingUnit", "lmtPriceOffset", "conditions", "conditionsCancelOrder", "conditionsIgnoreRth", "modelCode", "extOperator", "softDollarTier", "cashQty", "mifid2DecisionMaker", "mifid2DecisionAlgo", "mifid2ExecutionTrader", "mifid2ExecutionAlgo", "dontUseAutoPriceForHedge", "isOmsContainer", "discretionaryUpToLimitPrice", "autoCancelDate", "filledQuantity", "refFuturesConId", "autoCancelParent", "shareholder", "imbalanceOnly", "routeMarketableToBbo", "parentPermId", "usePriceMgmtAlgo", "duration", "postToAts", "advancedErrorOverride", "manualOrderTime", "minTradeQty", "minCompeteSize", "competeAgainstBestOffset", "midOffsetAtWhole", "midOffsetAtHalf", "customerAccount", "professionalCustomer", "bondAccruedInterest", "includeOvernight", "manualOrderIndicator", "submitter")
    class AlgoParamsEntry(_message.Message):
        __slots__ = ("key", "value")
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: str
        def __init__(self, key: _Optional[str] = ..., value: _Optional[str] = ...) -> None: ...
    class SmartComboRoutingParamsEntry(_message.Message):
        __slots__ = ("key", "value")
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: str
        def __init__(self, key: _Optional[str] = ..., value: _Optional[str] = ...) -> None: ...
    class OrderMiscOptionsEntry(_message.Message):
        __slots__ = ("key", "value")
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: str
        def __init__(self, key: _Optional[str] = ..., value: _Optional[str] = ...) -> None: ...
    CLIENTID_FIELD_NUMBER: _ClassVar[int]
    ORDERID_FIELD_NUMBER: _ClassVar[int]
    PERMID_FIELD_NUMBER: _ClassVar[int]
    PARENTID_FIELD_NUMBER: _ClassVar[int]
    ACTION_FIELD_NUMBER: _ClassVar[int]
    TOTALQUANTITY_FIELD_NUMBER: _ClassVar[int]
    DISPLAYSIZE_FIELD_NUMBER: _ClassVar[int]
    ORDERTYPE_FIELD_NUMBER: _ClassVar[int]
    LMTPRICE_FIELD_NUMBER: _ClassVar[int]
    AUXPRICE_FIELD_NUMBER: _ClassVar[int]
    TIF_FIELD_NUMBER: _ClassVar[int]
    ACCOUNT_FIELD_NUMBER: _ClassVar[int]
    SETTLINGFIRM_FIELD_NUMBER: _ClassVar[int]
    CLEARINGACCOUNT_FIELD_NUMBER: _ClassVar[int]
    CLEARINGINTENT_FIELD_NUMBER: _ClassVar[int]
    ALLORNONE_FIELD_NUMBER: _ClassVar[int]
    BLOCKORDER_FIELD_NUMBER: _ClassVar[int]
    HIDDEN_FIELD_NUMBER: _ClassVar[int]
    OUTSIDERTH_FIELD_NUMBER: _ClassVar[int]
    SWEEPTOFILL_FIELD_NUMBER: _ClassVar[int]
    PERCENTOFFSET_FIELD_NUMBER: _ClassVar[int]
    TRAILINGPERCENT_FIELD_NUMBER: _ClassVar[int]
    TRAILSTOPPRICE_FIELD_NUMBER: _ClassVar[int]
    MINQTY_FIELD_NUMBER: _ClassVar[int]
    GOODAFTERTIME_FIELD_NUMBER: _ClassVar[int]
    GOODTILLDATE_FIELD_NUMBER: _ClassVar[int]
    OCAGROUP_FIELD_NUMBER: _ClassVar[int]
    ORDERREF_FIELD_NUMBER: _ClassVar[int]
    RULE80A_FIELD_NUMBER: _ClassVar[int]
    OCATYPE_FIELD_NUMBER: _ClassVar[int]
    TRIGGERMETHOD_FIELD_NUMBER: _ClassVar[int]
    ACTIVESTARTTIME_FIELD_NUMBER: _ClassVar[int]
    ACTIVESTOPTIME_FIELD_NUMBER: _ClassVar[int]
    FAGROUP_FIELD_NUMBER: _ClassVar[int]
    FAMETHOD_FIELD_NUMBER: _ClassVar[int]
    FAPERCENTAGE_FIELD_NUMBER: _ClassVar[int]
    VOLATILITY_FIELD_NUMBER: _ClassVar[int]
    VOLATILITYTYPE_FIELD_NUMBER: _ClassVar[int]
    CONTINUOUSUPDATE_FIELD_NUMBER: _ClassVar[int]
    REFERENCEPRICETYPE_FIELD_NUMBER: _ClassVar[int]
    DELTANEUTRALORDERTYPE_FIELD_NUMBER: _ClassVar[int]
    DELTANEUTRALAUXPRICE_FIELD_NUMBER: _ClassVar[int]
    DELTANEUTRALCONID_FIELD_NUMBER: _ClassVar[int]
    DELTANEUTRALOPENCLOSE_FIELD_NUMBER: _ClassVar[int]
    DELTANEUTRALSHORTSALE_FIELD_NUMBER: _ClassVar[int]
    DELTANEUTRALSHORTSALESLOT_FIELD_NUMBER: _ClassVar[int]
    DELTANEUTRALDESIGNATEDLOCATION_FIELD_NUMBER: _ClassVar[int]
    SCALEINITLEVELSIZE_FIELD_NUMBER: _ClassVar[int]
    SCALESUBSLEVELSIZE_FIELD_NUMBER: _ClassVar[int]
    SCALEPRICEINCREMENT_FIELD_NUMBER: _ClassVar[int]
    SCALEPRICEADJUSTVALUE_FIELD_NUMBER: _ClassVar[int]
    SCALEPRICEADJUSTINTERVAL_FIELD_NUMBER: _ClassVar[int]
    SCALEPROFITOFFSET_FIELD_NUMBER: _ClassVar[int]
    SCALEAUTORESET_FIELD_NUMBER: _ClassVar[int]
    SCALEINITPOSITION_FIELD_NUMBER: _ClassVar[int]
    SCALEINITFILLQTY_FIELD_NUMBER: _ClassVar[int]
    SCALERANDOMPERCENT_FIELD_NUMBER: _ClassVar[int]
    SCALETABLE_FIELD_NUMBER: _ClassVar[int]
    HEDGETYPE_FIELD_NUMBER: _ClassVar[int]
    HEDGEPARAM_FIELD_NUMBER: _ClassVar[int]
    ALGOSTRATEGY_FIELD_NUMBER: _ClassVar[int]
    ALGOPARAMS_FIELD_NUMBER: _ClassVar[int]
    ALGOID_FIELD_NUMBER: _ClassVar[int]
    SMARTCOMBOROUTINGPARAMS_FIELD_NUMBER: _ClassVar[int]
    WHATIF_FIELD_NUMBER: _ClassVar[int]
    TRANSMIT_FIELD_NUMBER: _ClassVar[int]
    OVERRIDEPERCENTAGECONSTRAINTS_FIELD_NUMBER: _ClassVar[int]
    OPENCLOSE_FIELD_NUMBER: _ClassVar[int]
    ORIGIN_FIELD_NUMBER: _ClassVar[int]
    SHORTSALESLOT_FIELD_NUMBER: _ClassVar[int]
    DESIGNATEDLOCATION_FIELD_NUMBER: _ClassVar[int]
    EXEMPTCODE_FIELD_NUMBER: _ClassVar[int]
    DELTANEUTRALSETTLINGFIRM_FIELD_NUMBER: _ClassVar[int]
    DELTANEUTRALCLEARINGACCOUNT_FIELD_NUMBER: _ClassVar[int]
    DELTANEUTRALCLEARINGINTENT_FIELD_NUMBER: _ClassVar[int]
    DISCRETIONARYAMT_FIELD_NUMBER: _ClassVar[int]
    OPTOUTSMARTROUTING_FIELD_NUMBER: _ClassVar[int]
    STARTINGPRICE_FIELD_NUMBER: _ClassVar[int]
    STOCKREFPRICE_FIELD_NUMBER: _ClassVar[int]
    DELTA_FIELD_NUMBER: _ClassVar[int]
    STOCKRANGELOWER_FIELD_NUMBER: _ClassVar[int]
    STOCKRANGEUPPER_FIELD_NUMBER: _ClassVar[int]
    NOTHELD_FIELD_NUMBER: _ClassVar[int]
    ORDERMISCOPTIONS_FIELD_NUMBER: _ClassVar[int]
    SOLICITED_FIELD_NUMBER: _ClassVar[int]
    RANDOMIZESIZE_FIELD_NUMBER: _ClassVar[int]
    RANDOMIZEPRICE_FIELD_NUMBER: _ClassVar[int]
    REFERENCECONTRACTID_FIELD_NUMBER: _ClassVar[int]
    PEGGEDCHANGEAMOUNT_FIELD_NUMBER: _ClassVar[int]
    ISPEGGEDCHANGEAMOUNTDECREASE_FIELD_NUMBER: _ClassVar[int]
    REFERENCECHANGEAMOUNT_FIELD_NUMBER: _ClassVar[int]
    REFERENCEEXCHANGEID_FIELD_NUMBER: _ClassVar[int]
    ADJUSTEDORDERTYPE_FIELD_NUMBER: _ClassVar[int]
    TRIGGERPRICE_FIELD_NUMBER: _ClassVar[int]
    ADJUSTEDSTOPPRICE_FIELD_NUMBER: _ClassVar[int]
    ADJUSTEDSTOPLIMITPRICE_FIELD_NUMBER: _ClassVar[int]
    ADJUSTEDTRAILINGAMOUNT_FIELD_NUMBER: _ClassVar[int]
    ADJUSTABLETRAILINGUNIT_FIELD_NUMBER: _ClassVar[int]
    LMTPRICEOFFSET_FIELD_NUMBER: _ClassVar[int]
    CONDITIONS_FIELD_NUMBER: _ClassVar[int]
    CONDITIONSCANCELORDER_FIELD_NUMBER: _ClassVar[int]
    CONDITIONSIGNORERTH_FIELD_NUMBER: _ClassVar[int]
    MODELCODE_FIELD_NUMBER: _ClassVar[int]
    EXTOPERATOR_FIELD_NUMBER: _ClassVar[int]
    SOFTDOLLARTIER_FIELD_NUMBER: _ClassVar[int]
    CASHQTY_FIELD_NUMBER: _ClassVar[int]
    MIFID2DECISIONMAKER_FIELD_NUMBER: _ClassVar[int]
    MIFID2DECISIONALGO_FIELD_NUMBER: _ClassVar[int]
    MIFID2EXECUTIONTRADER_FIELD_NUMBER: _ClassVar[int]
    MIFID2EXECUTIONALGO_FIELD_NUMBER: _ClassVar[int]
    DONTUSEAUTOPRICEFORHEDGE_FIELD_NUMBER: _ClassVar[int]
    ISOMSCONTAINER_FIELD_NUMBER: _ClassVar[int]
    DISCRETIONARYUPTOLIMITPRICE_FIELD_NUMBER: _ClassVar[int]
    AUTOCANCELDATE_FIELD_NUMBER: _ClassVar[int]
    FILLEDQUANTITY_FIELD_NUMBER: _ClassVar[int]
    REFFUTURESCONID_FIELD_NUMBER: _ClassVar[int]
    AUTOCANCELPARENT_FIELD_NUMBER: _ClassVar[int]
    SHAREHOLDER_FIELD_NUMBER: _ClassVar[int]
    IMBALANCEONLY_FIELD_NUMBER: _ClassVar[int]
    ROUTEMARKETABLETOBBO_FIELD_NUMBER: _ClassVar[int]
    PARENTPERMID_FIELD_NUMBER: _ClassVar[int]
    USEPRICEMGMTALGO_FIELD_NUMBER: _ClassVar[int]
    DURATION_FIELD_NUMBER: _ClassVar[int]
    POSTTOATS_FIELD_NUMBER: _ClassVar[int]
    ADVANCEDERROROVERRIDE_FIELD_NUMBER: _ClassVar[int]
    MANUALORDERTIME_FIELD_NUMBER: _ClassVar[int]
    MINTRADEQTY_FIELD_NUMBER: _ClassVar[int]
    MINCOMPETESIZE_FIELD_NUMBER: _ClassVar[int]
    COMPETEAGAINSTBESTOFFSET_FIELD_NUMBER: _ClassVar[int]
    MIDOFFSETATWHOLE_FIELD_NUMBER: _ClassVar[int]
    MIDOFFSETATHALF_FIELD_NUMBER: _ClassVar[int]
    CUSTOMERACCOUNT_FIELD_NUMBER: _ClassVar[int]
    PROFESSIONALCUSTOMER_FIELD_NUMBER: _ClassVar[int]
    BONDACCRUEDINTEREST_FIELD_NUMBER: _ClassVar[int]
    INCLUDEOVERNIGHT_FIELD_NUMBER: _ClassVar[int]
    MANUALORDERINDICATOR_FIELD_NUMBER: _ClassVar[int]
    SUBMITTER_FIELD_NUMBER: _ClassVar[int]
    clientId: int
    orderId: int
    permId: int
    parentId: int
    action: str
    totalQuantity: str
    displaySize: int
    orderType: str
    lmtPrice: float
    auxPrice: float
    tif: str
    account: str
    settlingFirm: str
    clearingAccount: str
    clearingIntent: str
    allOrNone: bool
    blockOrder: bool
    hidden: bool
    outsideRth: bool
    sweepToFill: bool
    percentOffset: float
    trailingPercent: float
    trailStopPrice: float
    minQty: int
    goodAfterTime: str
    goodTillDate: str
    ocaGroup: str
    orderRef: str
    rule80A: str
    ocaType: int
    triggerMethod: int
    activeStartTime: str
    activeStopTime: str
    faGroup: str
    faMethod: str
    faPercentage: str
    volatility: float
    volatilityType: int
    continuousUpdate: bool
    referencePriceType: int
    deltaNeutralOrderType: str
    deltaNeutralAuxPrice: float
    deltaNeutralConId: int
    deltaNeutralOpenClose: str
    deltaNeutralShortSale: bool
    deltaNeutralShortSaleSlot: int
    deltaNeutralDesignatedLocation: str
    scaleInitLevelSize: int
    scaleSubsLevelSize: int
    scalePriceIncrement: float
    scalePriceAdjustValue: float
    scalePriceAdjustInterval: int
    scaleProfitOffset: float
    scaleAutoReset: bool
    scaleInitPosition: int
    scaleInitFillQty: int
    scaleRandomPercent: bool
    scaleTable: str
    hedgeType: str
    hedgeParam: str
    algoStrategy: str
    algoParams: _containers.ScalarMap[str, str]
    algoId: str
    smartComboRoutingParams: _containers.ScalarMap[str, str]
    whatIf: bool
    transmit: bool
    overridePercentageConstraints: bool
    openClose: str
    origin: int
    shortSaleSlot: int
    designatedLocation: str
    exemptCode: int
    deltaNeutralSettlingFirm: str
    deltaNeutralClearingAccount: str
    deltaNeutralClearingIntent: str
    discretionaryAmt: float
    optOutSmartRouting: bool
    startingPrice: float
    stockRefPrice: float
    delta: float
    stockRangeLower: float
    stockRangeUpper: float
    notHeld: bool
    orderMiscOptions: _containers.ScalarMap[str, str]
    solicited: bool
    randomizeSize: bool
    randomizePrice: bool
    referenceContractId: int
    peggedChangeAmount: float
    isPeggedChangeAmountDecrease: bool
    referenceChangeAmount: float
    referenceExchangeId: str
    adjustedOrderType: str
    triggerPrice: float
    adjustedStopPrice: float
    adjustedStopLimitPrice: float
    adjustedTrailingAmount: float
    adjustableTrailingUnit: int
    lmtPriceOffset: float
    conditions: _containers.RepeatedCompositeFieldContainer[_OrderCondition_pb2.OrderCondition]
    conditionsCancelOrder: bool
    conditionsIgnoreRth: bool
    modelCode: str
    extOperator: str
    softDollarTier: _SoftDollarTier_pb2.SoftDollarTier
    cashQty: float
    mifid2DecisionMaker: str
    mifid2DecisionAlgo: str
    mifid2ExecutionTrader: str
    mifid2ExecutionAlgo: str
    dontUseAutoPriceForHedge: bool
    isOmsContainer: bool
    discretionaryUpToLimitPrice: bool
    autoCancelDate: str
    filledQuantity: str
    refFuturesConId: int
    autoCancelParent: bool
    shareholder: str
    imbalanceOnly: bool
    routeMarketableToBbo: bool
    parentPermId: int
    usePriceMgmtAlgo: int
    duration: int
    postToAts: int
    advancedErrorOverride: str
    manualOrderTime: str
    minTradeQty: int
    minCompeteSize: int
    competeAgainstBestOffset: float
    midOffsetAtWhole: float
    midOffsetAtHalf: float
    customerAccount: str
    professionalCustomer: bool
    bondAccruedInterest: str
    includeOvernight: bool
    manualOrderIndicator: int
    submitter: str
    def __init__(self, clientId: _Optional[int] = ..., orderId: _Optional[int] = ..., permId: _Optional[int] = ..., parentId: _Optional[int] = ..., action: _Optional[str] = ..., totalQuantity: _Optional[str] = ..., displaySize: _Optional[int] = ..., orderType: _Optional[str] = ..., lmtPrice: _Optional[float] = ..., auxPrice: _Optional[float] = ..., tif: _Optional[str] = ..., account: _Optional[str] = ..., settlingFirm: _Optional[str] = ..., clearingAccount: _Optional[str] = ..., clearingIntent: _Optional[str] = ..., allOrNone: bool = ..., blockOrder: bool = ..., hidden: bool = ..., outsideRth: bool = ..., sweepToFill: bool = ..., percentOffset: _Optional[float] = ..., trailingPercent: _Optional[float] = ..., trailStopPrice: _Optional[float] = ..., minQty: _Optional[int] = ..., goodAfterTime: _Optional[str] = ..., goodTillDate: _Optional[str] = ..., ocaGroup: _Optional[str] = ..., orderRef: _Optional[str] = ..., rule80A: _Optional[str] = ..., ocaType: _Optional[int] = ..., triggerMethod: _Optional[int] = ..., activeStartTime: _Optional[str] = ..., activeStopTime: _Optional[str] = ..., faGroup: _Optional[str] = ..., faMethod: _Optional[str] = ..., faPercentage: _Optional[str] = ..., volatility: _Optional[float] = ..., volatilityType: _Optional[int] = ..., continuousUpdate: bool = ..., referencePriceType: _Optional[int] = ..., deltaNeutralOrderType: _Optional[str] = ..., deltaNeutralAuxPrice: _Optional[float] = ..., deltaNeutralConId: _Optional[int] = ..., deltaNeutralOpenClose: _Optional[str] = ..., deltaNeutralShortSale: bool = ..., deltaNeutralShortSaleSlot: _Optional[int] = ..., deltaNeutralDesignatedLocation: _Optional[str] = ..., scaleInitLevelSize: _Optional[int] = ..., scaleSubsLevelSize: _Optional[int] = ..., scalePriceIncrement: _Optional[float] = ..., scalePriceAdjustValue: _Optional[float] = ..., scalePriceAdjustInterval: _Optional[int] = ..., scaleProfitOffset: _Optional[float] = ..., scaleAutoReset: bool = ..., scaleInitPosition: _Optional[int] = ..., scaleInitFillQty: _Optional[int] = ..., scaleRandomPercent: bool = ..., scaleTable: _Optional[str] = ..., hedgeType: _Optional[str] = ..., hedgeParam: _Optional[str] = ..., algoStrategy: _Optional[str] = ..., algoParams: _Optional[_Mapping[str, str]] = ..., algoId: _Optional[str] = ..., smartComboRoutingParams: _Optional[_Mapping[str, str]] = ..., whatIf: bool = ..., transmit: bool = ..., overridePercentageConstraints: bool = ..., openClose: _Optional[str] = ..., origin: _Optional[int] = ..., shortSaleSlot: _Optional[int] = ..., designatedLocation: _Optional[str] = ..., exemptCode: _Optional[int] = ..., deltaNeutralSettlingFirm: _Optional[str] = ..., deltaNeutralClearingAccount: _Optional[str] = ..., deltaNeutralClearingIntent: _Optional[str] = ..., discretionaryAmt: _Optional[float] = ..., optOutSmartRouting: bool = ..., startingPrice: _Optional[float] = ..., stockRefPrice: _Optional[float] = ..., delta: _Optional[float] = ..., stockRangeLower: _Optional[float] = ..., stockRangeUpper: _Optional[float] = ..., notHeld: bool = ..., orderMiscOptions: _Optional[_Mapping[str, str]] = ..., solicited: bool = ..., randomizeSize: bool = ..., randomizePrice: bool = ..., referenceContractId: _Optional[int] = ..., peggedChangeAmount: _Optional[float] = ..., isPeggedChangeAmountDecrease: bool = ..., referenceChangeAmount: _Optional[float] = ..., referenceExchangeId: _Optional[str] = ..., adjustedOrderType: _Optional[str] = ..., triggerPrice: _Optional[float] = ..., adjustedStopPrice: _Optional[float] = ..., adjustedStopLimitPrice: _Optional[float] = ..., adjustedTrailingAmount: _Optional[float] = ..., adjustableTrailingUnit: _Optional[int] = ..., lmtPriceOffset: _Optional[float] = ..., conditions: _Optional[_Iterable[_Union[_OrderCondition_pb2.OrderCondition, _Mapping]]] = ..., conditionsCancelOrder: bool = ..., conditionsIgnoreRth: bool = ..., modelCode: _Optional[str] = ..., extOperator: _Optional[str] = ..., softDollarTier: _Optional[_Union[_SoftDollarTier_pb2.SoftDollarTier, _Mapping]] = ..., cashQty: _Optional[float] = ..., mifid2DecisionMaker: _Optional[str] = ..., mifid2DecisionAlgo: _Optional[str] = ..., mifid2ExecutionTrader: _Optional[str] = ..., mifid2ExecutionAlgo: _Optional[str] = ..., dontUseAutoPriceForHedge: bool = ..., isOmsContainer: bool = ..., discretionaryUpToLimitPrice: bool = ..., autoCancelDate: _Optional[str] = ..., filledQuantity: _Optional[str] = ..., refFuturesConId: _Optional[int] = ..., autoCancelParent: bool = ..., shareholder: _Optional[str] = ..., imbalanceOnly: bool = ..., routeMarketableToBbo: bool = ..., parentPermId: _Optional[int] = ..., usePriceMgmtAlgo: _Optional[int] = ..., duration: _Optional[int] = ..., postToAts: _Optional[int] = ..., advancedErrorOverride: _Optional[str] = ..., manualOrderTime: _Optional[str] = ..., minTradeQty: _Optional[int] = ..., minCompeteSize: _Optional[int] = ..., competeAgainstBestOffset: _Optional[float] = ..., midOffsetAtWhole: _Optional[float] = ..., midOffsetAtHalf: _Optional[float] = ..., customerAccount: _Optional[str] = ..., professionalCustomer: bool = ..., bondAccruedInterest: _Optional[str] = ..., includeOvernight: bool = ..., manualOrderIndicator: _Optional[int] = ..., submitter: _Optional[str] = ...) -> None: ...
