# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OrderBound.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'OrderBound.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10OrderBound.proto\x12\x08protobuf\"r\n\nOrderBound\x12\x13\n\x06permId\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x15\n\x08\x63lientId\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x14\n\x07orderId\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\t\n\x07_permIdB\x0b\n\t_clientIdB\n\n\x08_orderIdB:\n\x16\x63om.ib.client.protobufB\x0fOrderBoundProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OrderBound_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\017OrderBoundProto\252\002\016IBApi.protobuf'
  _globals['_ORDERBOUND']._serialized_start=30
  _globals['_ORDERBOUND']._serialized_end=144
# @@protoc_insertion_point(module_scope)
