# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PnL.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'PnL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tPnL.proto\x12\x08protobuf\"\x9f\x01\n\x03PnL\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08\x64\x61ilyPnL\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x1a\n\runrealizedPnL\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x18\n\x0brealizedPnL\x18\x04 \x01(\x01H\x03\x88\x01\x01\x42\x08\n\x06_reqIdB\x0b\n\t_dailyPnLB\x10\n\x0e_unrealizedPnLB\x0e\n\x0c_realizedPnLB3\n\x16\x63om.ib.client.protobufB\x08PnLProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PnL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\010PnLProto\252\002\016IBApi.protobuf'
  _globals['_PNL']._serialized_start=24
  _globals['_PNL']._serialized_end=183
# @@protoc_insertion_point(module_scope)
