# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PortfolioValue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'PortfolioValue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Contract_pb2 as Contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14PortfolioValue.proto\x12\x08protobuf\x1a\x0e\x43ontract.proto\"\xec\x02\n\x0ePortfolioValue\x12)\n\x08\x63ontract\x18\x01 \x01(\x0b\x32\x12.protobuf.ContractH\x00\x88\x01\x01\x12\x15\n\x08position\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bmarketPrice\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x18\n\x0bmarketValue\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12\x18\n\x0b\x61verageCost\x18\x05 \x01(\x01H\x04\x88\x01\x01\x12\x1a\n\runrealizedPNL\x18\x06 \x01(\x01H\x05\x88\x01\x01\x12\x18\n\x0brealizedPNL\x18\x07 \x01(\x01H\x06\x88\x01\x01\x12\x18\n\x0b\x61\x63\x63ountName\x18\x08 \x01(\tH\x07\x88\x01\x01\x42\x0b\n\t_contractB\x0b\n\t_positionB\x0e\n\x0c_marketPriceB\x0e\n\x0c_marketValueB\x0e\n\x0c_averageCostB\x10\n\x0e_unrealizedPNLB\x0e\n\x0c_realizedPNLB\x0e\n\x0c_accountNameB>\n\x16\x63om.ib.client.protobufB\x13PortfolioValueProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PortfolioValue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\023PortfolioValueProto\252\002\016IBApi.protobuf'
  _globals['_PORTFOLIOVALUE']._serialized_start=51
  _globals['_PORTFOLIOVALUE']._serialized_end=415
# @@protoc_insertion_point(module_scope)
