# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PositionMulti.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'PositionMulti.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Contract_pb2 as Contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13PositionMulti.proto\x12\x08protobuf\x1a\x0e\x43ontract.proto\"\xf3\x01\n\rPositionMulti\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x14\n\x07\x61\x63\x63ount\x18\x02 \x01(\tH\x01\x88\x01\x01\x12)\n\x08\x63ontract\x18\x03 \x01(\x0b\x32\x12.protobuf.ContractH\x02\x88\x01\x01\x12\x15\n\x08position\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x14\n\x07\x61vgCost\x18\x05 \x01(\x01H\x04\x88\x01\x01\x12\x16\n\tmodelCode\x18\x06 \x01(\tH\x05\x88\x01\x01\x42\x08\n\x06_reqIdB\n\n\x08_accountB\x0b\n\t_contractB\x0b\n\t_positionB\n\n\x08_avgCostB\x0c\n\n_modelCodeB=\n\x16\x63om.ib.client.protobufB\x12PositionMultiProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PositionMulti_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\022PositionMultiProto\252\002\016IBApi.protobuf'
  _globals['_POSITIONMULTI']._serialized_start=50
  _globals['_POSITIONMULTI']._serialized_end=293
# @@protoc_insertion_point(module_scope)
