# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PriceIncrement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'PriceIncrement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14PriceIncrement.proto\x12\x08protobuf\"X\n\x0ePriceIncrement\x12\x14\n\x07lowEdge\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x16\n\tincrement\x18\x02 \x01(\x01H\x01\x88\x01\x01\x42\n\n\x08_lowEdgeB\x0c\n\n_incrementB>\n\x16\x63om.ib.client.protobufB\x13PriceIncrementProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PriceIncrement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\023PriceIncrementProto\252\002\016IBApi.protobuf'
  _globals['_PRICEINCREMENT']._serialized_start=34
  _globals['_PRICEINCREMENT']._serialized_end=122
# @@protoc_insertion_point(module_scope)
