# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ScannerSubscriptionRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ScannerSubscriptionRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ScannerSubscription_pb2 as ScannerSubscription__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ScannerSubscriptionRequest.proto\x12\x08protobuf\x1a\x19ScannerSubscription.proto\"\x93\x01\n\x1aScannerSubscriptionRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12?\n\x13scannerSubscription\x18\x02 \x01(\x0b\x32\x1d.protobuf.ScannerSubscriptionH\x01\x88\x01\x01\x42\x08\n\x06_reqIdB\x16\n\x14_scannerSubscriptionBJ\n\x16\x63om.ib.client.protobufB\x1fScannerSubscriptionRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ScannerSubscriptionRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\037ScannerSubscriptionRequestProto\252\002\016IBApi.protobuf'
  _globals['_SCANNERSUBSCRIPTIONREQUEST']._serialized_start=74
  _globals['_SCANNERSUBSCRIPTIONREQUEST']._serialized_end=221
# @@protoc_insertion_point(module_scope)
