# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ScannerDataElement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ScannerDataElement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Contract_pb2 as Contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18ScannerDataElement.proto\x12\x08protobuf\x1a\x0e\x43ontract.proto\"\xa6\x02\n\x12ScannerDataElement\x12\x11\n\x04rank\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12)\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x12.protobuf.ContractH\x01\x88\x01\x01\x12\x17\n\nmarketName\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08\x64istance\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x16\n\tbenchmark\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x17\n\nprojection\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x15\n\x08\x63omboKey\x18\x07 \x01(\tH\x06\x88\x01\x01\x42\x07\n\x05_rankB\x0b\n\t_contractB\r\n\x0b_marketNameB\x0b\n\t_distanceB\x0c\n\n_benchmarkB\r\n\x0b_projectionB\x0b\n\t_comboKeyBB\n\x16\x63om.ib.client.protobufB\x17ScannerDataElementProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ScannerDataElement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\027ScannerDataElementProto\252\002\016IBApi.protobuf'
  _globals['_SCANNERDATAELEMENT']._serialized_start=55
  _globals['_SCANNERDATAELEMENT']._serialized_end=349
# @@protoc_insertion_point(module_scope)
