# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SecDefOptParameter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SecDefOptParameter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18SecDefOptParameter.proto\x12\x08protobuf\"\x82\x02\n\x12SecDefOptParameter\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08\x65xchange\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1c\n\x0funderlyingConId\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x19\n\x0ctradingClass\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x17\n\nmultiplier\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x13\n\x0b\x65xpirations\x18\x06 \x03(\t\x12\x0f\n\x07strikes\x18\x07 \x03(\x01\x42\x08\n\x06_reqIdB\x0b\n\t_exchangeB\x12\n\x10_underlyingConIdB\x0f\n\r_tradingClassB\r\n\x0b_multiplierBB\n\x16\x63om.ib.client.protobufB\x17SecDefOptParameterProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SecDefOptParameter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\027SecDefOptParameterProto\252\002\016IBApi.protobuf'
  _globals['_SECDEFOPTPARAMETER']._serialized_start=39
  _globals['_SECDEFOPTPARAMETER']._serialized_end=297
# @@protoc_insertion_point(module_scope)
