# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SecDefOptParamsRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SecDefOptParamsRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSecDefOptParamsRequest.proto\x12\x08protobuf\"\x82\x02\n\x16SecDefOptParamsRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x1d\n\x10underlyingSymbol\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1b\n\x0e\x66utFopExchange\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1e\n\x11underlyingSecType\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x1c\n\x0funderlyingConId\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\x08\n\x06_reqIdB\x13\n\x11_underlyingSymbolB\x11\n\x0f_futFopExchangeB\x14\n\x12_underlyingSecTypeB\x12\n\x10_underlyingConIdBF\n\x16\x63om.ib.client.protobufB\x1bSecDefOptParamsRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SecDefOptParamsRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\033SecDefOptParamsRequestProto\252\002\016IBApi.protobuf'
  _globals['_SECDEFOPTPARAMSREQUEST']._serialized_start=43
  _globals['_SECDEFOPTPARAMSREQUEST']._serialized_end=301
# @@protoc_insertion_point(module_scope)
