# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SymbolSamples.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'SymbolSamples.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ContractDescription_pb2 as ContractDescription__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SymbolSamples.proto\x12\x08protobuf\x1a\x19\x43ontractDescription.proto\"j\n\rSymbolSamples\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12;\n\x14\x63ontractDescriptions\x18\x02 \x03(\x0b\x32\x1d.protobuf.ContractDescriptionB\x08\n\x06_reqIdB=\n\x16\x63om.ib.client.protobufB\x12SymbolSamplesProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SymbolSamples_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\022SymbolSamplesProto\252\002\016IBApi.protobuf'
  _globals['_SYMBOLSAMPLES']._serialized_start=60
  _globals['_SYMBOLSAMPLES']._serialized_end=166
# @@protoc_insertion_point(module_scope)
