# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TickOptionComputation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TickOptionComputation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bTickOptionComputation.proto\x12\x08protobuf\"\x8f\x03\n\x15TickOptionComputation\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08tickType\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x17\n\ntickAttrib\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x17\n\nimpliedVol\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12\x12\n\x05\x64\x65lta\x18\x05 \x01(\x01H\x04\x88\x01\x01\x12\x15\n\x08optPrice\x18\x06 \x01(\x01H\x05\x88\x01\x01\x12\x17\n\npvDividend\x18\x07 \x01(\x01H\x06\x88\x01\x01\x12\x12\n\x05gamma\x18\x08 \x01(\x01H\x07\x88\x01\x01\x12\x11\n\x04vega\x18\t \x01(\x01H\x08\x88\x01\x01\x12\x12\n\x05theta\x18\n \x01(\x01H\t\x88\x01\x01\x12\x15\n\x08undPrice\x18\x0b \x01(\x01H\n\x88\x01\x01\x42\x08\n\x06_reqIdB\x0b\n\t_tickTypeB\r\n\x0b_tickAttribB\r\n\x0b_impliedVolB\x08\n\x06_deltaB\x0b\n\t_optPriceB\r\n\x0b_pvDividendB\x08\n\x06_gammaB\x07\n\x05_vegaB\x08\n\x06_thetaB\x0b\n\t_undPriceBE\n\x16\x63om.ib.client.protobufB\x1aTickOptionComputationProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TickOptionComputation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\032TickOptionComputationProto\252\002\016IBApi.protobuf'
  _globals['_TICKOPTIONCOMPUTATION']._serialized_start=42
  _globals['_TICKOPTIONCOMPUTATION']._serialized_end=441
# @@protoc_insertion_point(module_scope)
