# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TickPrice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TickPrice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fTickPrice.proto\x12\x08protobuf\"\xab\x01\n\tTickPrice\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08tickType\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x12\n\x05price\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x11\n\x04size\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08\x61ttrMask\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\x08\n\x06_reqIdB\x0b\n\t_tickTypeB\x08\n\x06_priceB\x07\n\x05_sizeB\x0b\n\t_attrMaskB9\n\x16\x63om.ib.client.protobufB\x0eTickPriceProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TickPrice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\016TickPriceProto\252\002\016IBApi.protobuf'
  _globals['_TICKPRICE']._serialized_start=30
  _globals['_TICKPRICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
