# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TickAttribLast.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TickAttribLast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14TickAttribLast.proto\x12\x08protobuf\"^\n\x0eTickAttribLast\x12\x16\n\tpastLimit\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x17\n\nunreported\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\x0c\n\n_pastLimitB\r\n\x0b_unreportedB>\n\x16\x63om.ib.client.protobufB\x13TickAttribLastProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TickAttribLast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\023TickAttribLastProto\252\002\016IBApi.protobuf'
  _globals['_TICKATTRIBLAST']._serialized_start=34
  _globals['_TICKATTRIBLAST']._serialized_end=128
# @@protoc_insertion_point(module_scope)
