# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TickByTickData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TickByTickData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import HistoricalTickLast_pb2 as HistoricalTickLast__pb2
from . import HistoricalTickBidAsk_pb2 as HistoricalTickBidAsk__pb2
from . import HistoricalTick_pb2 as HistoricalTick__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14TickByTickData.proto\x12\x08protobuf\x1a\x18HistoricalTickLast.proto\x1a\x1aHistoricalTickBidAsk.proto\x1a\x14HistoricalTick.proto\"\x92\x02\n\x0eTickByTickData\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x01\x88\x01\x01\x12\x15\n\x08tickType\x18\x02 \x01(\x05H\x02\x88\x01\x01\x12:\n\x12historicalTickLast\x18\x03 \x01(\x0b\x32\x1c.protobuf.HistoricalTickLastH\x00\x12>\n\x14historicalTickBidAsk\x18\x04 \x01(\x0b\x32\x1e.protobuf.HistoricalTickBidAskH\x00\x12:\n\x16historicalTickMidPoint\x18\x05 \x01(\x0b\x32\x18.protobuf.HistoricalTickH\x00\x42\x06\n\x04tickB\x08\n\x06_reqIdB\x0b\n\t_tickTypeB>\n\x16\x63om.ib.client.protobufB\x13TickByTickDataProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TickByTickData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\023TickByTickDataProto\252\002\016IBApi.protobuf'
  _globals['_TICKBYTICKDATA']._serialized_start=111
  _globals['_TICKBYTICKDATA']._serialized_end=385
# @@protoc_insertion_point(module_scope)
