# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: VerifyRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'VerifyRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13VerifyRequest.proto\x12\x08protobuf\"Y\n\rVerifyRequest\x12\x14\n\x07\x61piName\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\napiVersion\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_apiNameB\r\n\x0b_apiVersionB=\n\x16\x63om.ib.client.protobufB\x12VerifyRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VerifyRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\022VerifyRequestProto\252\002\016IBApi.protobuf'
  _globals['_VERIFYREQUEST']._serialized_start=33
  _globals['_VERIFYREQUEST']._serialized_end=122
# @@protoc_insertion_point(module_scope)
