# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: VerifyMessageRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'VerifyMessageRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aVerifyMessageRequest.proto\x12\x08protobuf\"8\n\x14VerifyMessageRequest\x12\x14\n\x07\x61piData\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_apiDataBD\n\x16\x63om.ib.client.protobufB\x19VerifyMessageRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VerifyMessageRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\031VerifyMessageRequestProto\252\002\016IBApi.protobuf'
  _globals['_VERIFYMESSAGEREQUEST']._serialized_start=40
  _globals['_VERIFYMESSAGEREQUEST']._serialized_end=96
# @@protoc_insertion_point(module_scope)
