# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WshEventDataRequest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'WshEventDataRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19WshEventDataRequest.proto\x12\x08protobuf\"\xef\x02\n\x13WshEventDataRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05\x63onId\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x13\n\x06\x66ilter\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1a\n\rfillWatchlist\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12\x1a\n\rfillPortfolio\x18\x05 \x01(\x08H\x04\x88\x01\x01\x12\x1c\n\x0f\x66illCompetitors\x18\x06 \x01(\x08H\x05\x88\x01\x01\x12\x16\n\tstartDate\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x14\n\x07\x65ndDate\x18\x08 \x01(\tH\x07\x88\x01\x01\x12\x17\n\ntotalLimit\x18\t \x01(\x05H\x08\x88\x01\x01\x42\x08\n\x06_reqIdB\x08\n\x06_conIdB\t\n\x07_filterB\x10\n\x0e_fillWatchlistB\x10\n\x0e_fillPortfolioB\x12\n\x10_fillCompetitorsB\x0c\n\n_startDateB\n\n\x08_endDateB\r\n\x0b_totalLimitBC\n\x16\x63om.ib.client.protobufB\x18WshEventDataRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WshEventDataRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\030WshEventDataRequestProto\252\002\016IBApi.protobuf'
  _globals['_WSHEVENTDATAREQUEST']._serialized_start=40
  _globals['_WSHEVENTDATAREQUEST']._serialized_end=407
# @@protoc_insertion_point(module_scope)
