"""Protobuf wire-framing constants and per-message gating table.

This is the source of truth for two things:

1. ``PROTOBUF_MSG_ID`` — the +200 sentinel that distinguishes protobuf
   bodies from legacy NUL-separated bodies on the wire. Every protobuf
   message is sent with ``wire_msgId = canonical + 200``; receivers
   strip the 200 to recover the canonical id and route to the protobuf
   decoder. (See IBKR ``ibapi/comm.py:19-33`` and ``ibapi/client.py:601-617``
   for the authoritative wire framing.)

2. ``PROTOBUF_MSG_IDS`` — per-canonical-msgId gating dict mapping each
   outbound message to the minimum ``serverVersion`` at which IBKR
   accepts it as protobuf. Below that gate the binary path stays in
   use; above it ``Client.useProtoBuf(msgId)`` returns ``True`` and the
   caller emits protobuf instead. The table mirrors IBKR's
   ``ibapi/common.py:55-136`` verbatim and must stay in sync.

Both halves of the API (binary and protobuf) coexist indefinitely — a
TWS / IB Gateway older than the relevant per-family gate keeps working
on the binary path. We never force protobuf on a server that doesn't
advertise support.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Final

# --- Per-message-family minimum server-version gates ----------------------
# Re-exported from ``_server_versions.py`` (single source of truth for
# every MIN_SERVER_VER_* constant). Listed here for readability of the
# PROTOBUF_MSG_IDS table below.
from ._server_versions import (
    MIN_SERVER_VER_PROTOBUF,
    MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS,
    MIN_SERVER_VER_PROTOBUF_COMPLETED_ORDER,
    MIN_SERVER_VER_PROTOBUF_CONTRACT_DATA,
    MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    MIN_SERVER_VER_PROTOBUF_MARKET_DATA,
    MIN_SERVER_VER_PROTOBUF_NEWS_DATA,
    MIN_SERVER_VER_PROTOBUF_PLACE_ORDER,
    MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_1,
    MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_2,
    MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    MIN_SERVER_VER_PROTOBUF_SCAN_DATA,
)

__all__ = [
    "MIN_SERVER_VER_PROTOBUF",
    "MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS",
    "MIN_SERVER_VER_PROTOBUF_COMPLETED_ORDER",
    "MIN_SERVER_VER_PROTOBUF_CONTRACT_DATA",
    "MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA",
    "MIN_SERVER_VER_PROTOBUF_MARKET_DATA",
    "MIN_SERVER_VER_PROTOBUF_NEWS_DATA",
    "MIN_SERVER_VER_PROTOBUF_PLACE_ORDER",
    "MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_1",
    "MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_2",
    "MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3",
    "MIN_SERVER_VER_PROTOBUF_SCAN_DATA",
    "PROTOBUF_MSG_ID",
    "PROTOBUF_MSG_IDS",
]

# --- Wire sentinel --------------------------------------------------------
# A wire ``msgId`` greater than this means the body is a protobuf payload;
# the canonical id is recovered by subtracting this constant. Sender
# adds it via ``Client.sendProto``.
PROTOBUF_MSG_ID: Final = 200

# --- Canonical outbound message IDs --------------------------------------
# Mirrored from ibapi/message.py OUT enum. Kept as raw integer constants
# rather than an Enum so existing call sites that pass integer literals
# to ``Client.send`` continue to work without renaming.
REQ_MKT_DATA: Final = 1
CANCEL_MKT_DATA: Final = 2
PLACE_ORDER: Final = 3
CANCEL_ORDER: Final = 4
REQ_OPEN_ORDERS: Final = 5
REQ_ACCT_DATA: Final = 6
REQ_EXECUTIONS: Final = 7
REQ_IDS: Final = 8
REQ_CONTRACT_DATA: Final = 9
REQ_MKT_DEPTH: Final = 10
CANCEL_MKT_DEPTH: Final = 11
REQ_NEWS_BULLETINS: Final = 12
CANCEL_NEWS_BULLETINS: Final = 13
SET_SERVER_LOGLEVEL: Final = 14
REQ_AUTO_OPEN_ORDERS: Final = 15
REQ_ALL_OPEN_ORDERS: Final = 16
REQ_MANAGED_ACCTS: Final = 17
REQ_FA: Final = 18
REPLACE_FA: Final = 19
REQ_HISTORICAL_DATA: Final = 20
EXERCISE_OPTIONS: Final = 21
REQ_SCANNER_SUBSCRIPTION: Final = 22
CANCEL_SCANNER_SUBSCRIPTION: Final = 23
REQ_SCANNER_PARAMETERS: Final = 24
CANCEL_HISTORICAL_DATA: Final = 25
REQ_CURRENT_TIME: Final = 49
REQ_REAL_TIME_BARS: Final = 50
CANCEL_REAL_TIME_BARS: Final = 51
REQ_FUNDAMENTAL_DATA: Final = 52
CANCEL_FUNDAMENTAL_DATA: Final = 53
REQ_CALC_IMPLIED_VOLAT: Final = 54
REQ_CALC_OPTION_PRICE: Final = 55
CANCEL_CALC_IMPLIED_VOLAT: Final = 56
CANCEL_CALC_OPTION_PRICE: Final = 57
REQ_GLOBAL_CANCEL: Final = 58
REQ_MARKET_DATA_TYPE: Final = 59
REQ_POSITIONS: Final = 61
REQ_ACCOUNT_SUMMARY: Final = 62
CANCEL_ACCOUNT_SUMMARY: Final = 63
CANCEL_POSITIONS: Final = 64
VERIFY_REQUEST: Final = 65
VERIFY_MESSAGE: Final = 66
QUERY_DISPLAY_GROUPS: Final = 67
SUBSCRIBE_TO_GROUP_EVENTS: Final = 68
UPDATE_DISPLAY_GROUP: Final = 69
UNSUBSCRIBE_FROM_GROUP_EVENTS: Final = 70
START_API: Final = 71
REQ_POSITIONS_MULTI: Final = 74
CANCEL_POSITIONS_MULTI: Final = 75
REQ_ACCOUNT_UPDATES_MULTI: Final = 76
CANCEL_ACCOUNT_UPDATES_MULTI: Final = 77
REQ_SEC_DEF_OPT_PARAMS: Final = 78
REQ_SOFT_DOLLAR_TIERS: Final = 79
REQ_FAMILY_CODES: Final = 80
REQ_MATCHING_SYMBOLS: Final = 81
REQ_MKT_DEPTH_EXCHANGES: Final = 82
REQ_SMART_COMPONENTS: Final = 83
REQ_NEWS_ARTICLE: Final = 84
REQ_NEWS_PROVIDERS: Final = 85
REQ_HISTORICAL_NEWS: Final = 86
REQ_HEAD_TIMESTAMP: Final = 87
REQ_HISTOGRAM_DATA: Final = 88
CANCEL_HISTOGRAM_DATA: Final = 89
CANCEL_HEAD_TIMESTAMP: Final = 90
REQ_MARKET_RULE: Final = 91
REQ_PNL: Final = 92
CANCEL_PNL: Final = 93
REQ_PNL_SINGLE: Final = 94
CANCEL_PNL_SINGLE: Final = 95
REQ_HISTORICAL_TICKS: Final = 96
REQ_TICK_BY_TICK_DATA: Final = 97
CANCEL_TICK_BY_TICK_DATA: Final = 98
REQ_COMPLETED_ORDERS: Final = 99
REQ_WSH_META_DATA: Final = 100
CANCEL_WSH_META_DATA: Final = 101
REQ_WSH_EVENT_DATA: Final = 102
CANCEL_WSH_EVENT_DATA: Final = 103
REQ_USER_INFO: Final = 104
REQ_CURRENT_TIME_IN_MILLIS: Final = 105
CANCEL_CONTRACT_DATA: Final = 106
CANCEL_HISTORICAL_TICKS: Final = 107
REQ_CONFIG: Final = 108
UPDATE_CONFIG: Final = 109

# --- Per-msgId gate table -------------------------------------------------
# Mirror of ibapi/common.py:55-136 PROTOBUF_MSG_IDS. Each entry maps a
# canonical outbound msgId to the minimum serverVersion at which the
# IBKR server accepts it as protobuf. Messages NOT in this table never
# go protobuf — Client.useProtoBuf(msgId) returns False for them.
PROTOBUF_MSG_IDS: Final[Mapping[int, int]] = {
    REQ_EXECUTIONS: MIN_SERVER_VER_PROTOBUF,
    PLACE_ORDER: MIN_SERVER_VER_PROTOBUF_PLACE_ORDER,
    CANCEL_ORDER: MIN_SERVER_VER_PROTOBUF_PLACE_ORDER,
    REQ_GLOBAL_CANCEL: MIN_SERVER_VER_PROTOBUF_PLACE_ORDER,
    REQ_ALL_OPEN_ORDERS: MIN_SERVER_VER_PROTOBUF_COMPLETED_ORDER,
    REQ_AUTO_OPEN_ORDERS: MIN_SERVER_VER_PROTOBUF_COMPLETED_ORDER,
    REQ_OPEN_ORDERS: MIN_SERVER_VER_PROTOBUF_COMPLETED_ORDER,
    REQ_COMPLETED_ORDERS: MIN_SERVER_VER_PROTOBUF_COMPLETED_ORDER,
    REQ_CONTRACT_DATA: MIN_SERVER_VER_PROTOBUF_CONTRACT_DATA,
    REQ_MKT_DATA: MIN_SERVER_VER_PROTOBUF_MARKET_DATA,
    CANCEL_MKT_DATA: MIN_SERVER_VER_PROTOBUF_MARKET_DATA,
    REQ_MKT_DEPTH: MIN_SERVER_VER_PROTOBUF_MARKET_DATA,
    CANCEL_MKT_DEPTH: MIN_SERVER_VER_PROTOBUF_MARKET_DATA,
    REQ_MARKET_DATA_TYPE: MIN_SERVER_VER_PROTOBUF_MARKET_DATA,
    REQ_ACCT_DATA: MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS,
    REQ_MANAGED_ACCTS: MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS,
    REQ_POSITIONS: MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS,
    CANCEL_POSITIONS: MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS,
    REQ_ACCOUNT_SUMMARY: MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS,
    CANCEL_ACCOUNT_SUMMARY: MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS,
    REQ_POSITIONS_MULTI: MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS,
    CANCEL_POSITIONS_MULTI: MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS,
    REQ_ACCOUNT_UPDATES_MULTI: MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS,
    CANCEL_ACCOUNT_UPDATES_MULTI: MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS,
    REQ_HISTORICAL_DATA: MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    CANCEL_HISTORICAL_DATA: MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    REQ_REAL_TIME_BARS: MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    CANCEL_REAL_TIME_BARS: MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    REQ_HEAD_TIMESTAMP: MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    CANCEL_HEAD_TIMESTAMP: MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    REQ_HISTOGRAM_DATA: MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    CANCEL_HISTOGRAM_DATA: MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    REQ_HISTORICAL_TICKS: MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    REQ_TICK_BY_TICK_DATA: MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    CANCEL_TICK_BY_TICK_DATA: MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA,
    REQ_NEWS_BULLETINS: MIN_SERVER_VER_PROTOBUF_NEWS_DATA,
    CANCEL_NEWS_BULLETINS: MIN_SERVER_VER_PROTOBUF_NEWS_DATA,
    REQ_NEWS_ARTICLE: MIN_SERVER_VER_PROTOBUF_NEWS_DATA,
    REQ_NEWS_PROVIDERS: MIN_SERVER_VER_PROTOBUF_NEWS_DATA,
    REQ_HISTORICAL_NEWS: MIN_SERVER_VER_PROTOBUF_NEWS_DATA,
    REQ_WSH_META_DATA: MIN_SERVER_VER_PROTOBUF_NEWS_DATA,
    CANCEL_WSH_META_DATA: MIN_SERVER_VER_PROTOBUF_NEWS_DATA,
    REQ_WSH_EVENT_DATA: MIN_SERVER_VER_PROTOBUF_NEWS_DATA,
    CANCEL_WSH_EVENT_DATA: MIN_SERVER_VER_PROTOBUF_NEWS_DATA,
    REQ_SCANNER_PARAMETERS: MIN_SERVER_VER_PROTOBUF_SCAN_DATA,
    REQ_SCANNER_SUBSCRIPTION: MIN_SERVER_VER_PROTOBUF_SCAN_DATA,
    CANCEL_SCANNER_SUBSCRIPTION: MIN_SERVER_VER_PROTOBUF_SCAN_DATA,
    REQ_FUNDAMENTAL_DATA: MIN_SERVER_VER_PROTOBUF_SCAN_DATA,
    CANCEL_FUNDAMENTAL_DATA: MIN_SERVER_VER_PROTOBUF_SCAN_DATA,
    REQ_PNL: MIN_SERVER_VER_PROTOBUF_SCAN_DATA,
    CANCEL_PNL: MIN_SERVER_VER_PROTOBUF_SCAN_DATA,
    REQ_PNL_SINGLE: MIN_SERVER_VER_PROTOBUF_SCAN_DATA,
    CANCEL_PNL_SINGLE: MIN_SERVER_VER_PROTOBUF_SCAN_DATA,
    REQ_FA: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_1,
    REPLACE_FA: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_1,
    EXERCISE_OPTIONS: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_1,
    REQ_CALC_IMPLIED_VOLAT: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_1,
    CANCEL_CALC_IMPLIED_VOLAT: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_1,
    REQ_CALC_OPTION_PRICE: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_1,
    CANCEL_CALC_OPTION_PRICE: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_1,
    REQ_SEC_DEF_OPT_PARAMS: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_2,
    REQ_SOFT_DOLLAR_TIERS: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_2,
    REQ_FAMILY_CODES: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_2,
    REQ_MATCHING_SYMBOLS: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_2,
    REQ_SMART_COMPONENTS: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_2,
    REQ_MARKET_RULE: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_2,
    REQ_USER_INFO: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_2,
    REQ_IDS: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    REQ_CURRENT_TIME: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    REQ_CURRENT_TIME_IN_MILLIS: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    START_API: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    SET_SERVER_LOGLEVEL: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    VERIFY_REQUEST: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    VERIFY_MESSAGE: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    QUERY_DISPLAY_GROUPS: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    SUBSCRIBE_TO_GROUP_EVENTS: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    UPDATE_DISPLAY_GROUP: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    UNSUBSCRIBE_FROM_GROUP_EVENTS: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
    REQ_MKT_DEPTH_EXCHANGES: MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3,
}
