"""Minimum-server-version constants for the IBKR API gating.

Every wire-protocol field, message family, and capability that IBKR has
ever shipped is gated by a minimum server version. ``Client.reqXxx``
methods must check ``self._serverVersion >= MIN_SERVER_VER_X`` before
writing a gated field, and ``Decoder.processXxxMsg`` methods must
likewise gate conditional reads. Mismatched gates produce malformed
wire frames the server can't parse OR mis-decoded responses where we
read fields the server never sent.

This module mirrors ``ibapi/server_versions.py`` from IBKR's official
Python reference client. Update by re-syncing against that file
when bumping ``MAX_CLIENT_VER``.

Constants below the protobuf cutoff (201) are kept too even though our
modern client only negotiates >= MIN_CLIENT_VER. They're available for
older-server-compat conditional reads that the binary decoder still
performs (e.g. PRE_OPEN_BID_ASK at 132, MARKET_CAP_PRICE at 131).
"""

from __future__ import annotations

from typing import Final

# --- Pre-100 (legacy, listed for completeness; we never negotiate below 100)
MIN_SERVER_VER_PTA_ORDERS: Final = 39
MIN_SERVER_VER_FUNDAMENTAL_DATA: Final = 40
MIN_SERVER_VER_DELTA_NEUTRAL: Final = 40
MIN_SERVER_VER_CONTRACT_DATA_CHAIN: Final = 40
MIN_SERVER_VER_SCALE_ORDERS2: Final = 40
MIN_SERVER_VER_ALGO_ORDERS: Final = 41
MIN_SERVER_VER_EXECUTION_DATA_CHAIN: Final = 42
MIN_SERVER_VER_NOT_HELD: Final = 44
MIN_SERVER_VER_SEC_ID_TYPE: Final = 45
MIN_SERVER_VER_PLACE_ORDER_CONID: Final = 46
MIN_SERVER_VER_REQ_MKT_DATA_CONID: Final = 47
MIN_SERVER_VER_REQ_CALC_IMPLIED_VOLAT: Final = 49
MIN_SERVER_VER_REQ_CALC_OPTION_PRICE: Final = 50
MIN_SERVER_VER_SSHORTX_OLD: Final = 51
MIN_SERVER_VER_SSHORTX: Final = 52
MIN_SERVER_VER_REQ_GLOBAL_CANCEL: Final = 53
MIN_SERVER_VER_HEDGE_ORDERS: Final = 54
MIN_SERVER_VER_REQ_MARKET_DATA_TYPE: Final = 55
MIN_SERVER_VER_OPT_OUT_SMART_ROUTING: Final = 56
MIN_SERVER_VER_SMART_COMBO_ROUTING_PARAMS: Final = 57
MIN_SERVER_VER_DELTA_NEUTRAL_CONID: Final = 58
MIN_SERVER_VER_SCALE_ORDERS3: Final = 60
MIN_SERVER_VER_ORDER_COMBO_LEGS_PRICE: Final = 61
MIN_SERVER_VER_TRAILING_PERCENT: Final = 62
MIN_SERVER_VER_DELTA_NEUTRAL_OPEN_CLOSE: Final = 66
MIN_SERVER_VER_POSITIONS: Final = 67
MIN_SERVER_VER_ACCOUNT_SUMMARY: Final = 67
MIN_SERVER_VER_TRADING_CLASS: Final = 68
MIN_SERVER_VER_SCALE_TABLE: Final = 69
MIN_SERVER_VER_LINKING: Final = 70
MIN_SERVER_VER_ALGO_ID: Final = 71
MIN_SERVER_VER_OPTIONAL_CAPABILITIES: Final = 72
MIN_SERVER_VER_ORDER_SOLICITED: Final = 73
MIN_SERVER_VER_LINKING_AUTH: Final = 74
MIN_SERVER_VER_PRIMARYEXCH: Final = 75
MIN_SERVER_VER_RANDOMIZE_SIZE_AND_PRICE: Final = 76

# --- Modern (100+ — what we actually negotiate)
MIN_SERVER_VER_FRACTIONAL_POSITIONS: Final = 101
MIN_SERVER_VER_PEGGED_TO_BENCHMARK: Final = 102
MIN_SERVER_VER_MODELS_SUPPORT: Final = 103
MIN_SERVER_VER_SEC_DEF_OPT_PARAMS_REQ: Final = 104
MIN_SERVER_VER_EXT_OPERATOR: Final = 105
MIN_SERVER_VER_SOFT_DOLLAR_TIER: Final = 106
MIN_SERVER_VER_REQ_FAMILY_CODES: Final = 107
MIN_SERVER_VER_REQ_MATCHING_SYMBOLS: Final = 108
MIN_SERVER_VER_PAST_LIMIT: Final = 109
MIN_SERVER_VER_MD_SIZE_MULTIPLIER: Final = 110
MIN_SERVER_VER_CASH_QTY: Final = 111
MIN_SERVER_VER_REQ_MKT_DEPTH_EXCHANGES: Final = 112
MIN_SERVER_VER_TICK_NEWS: Final = 113
MIN_SERVER_VER_REQ_SMART_COMPONENTS: Final = 114
MIN_SERVER_VER_REQ_NEWS_PROVIDERS: Final = 115
MIN_SERVER_VER_REQ_NEWS_ARTICLE: Final = 116
MIN_SERVER_VER_REQ_HISTORICAL_NEWS: Final = 117
MIN_SERVER_VER_REQ_HEAD_TIMESTAMP: Final = 118
MIN_SERVER_VER_REQ_HISTOGRAM: Final = 119
MIN_SERVER_VER_SERVICE_DATA_TYPE: Final = 120
MIN_SERVER_VER_AGG_GROUP: Final = 121
MIN_SERVER_VER_UNDERLYING_INFO: Final = 122
MIN_SERVER_VER_CANCEL_HEADTIMESTAMP: Final = 123
MIN_SERVER_VER_SYNT_REALTIME_BARS: Final = 124
MIN_SERVER_VER_CFD_REROUTE: Final = 125
MIN_SERVER_VER_MARKET_RULES: Final = 126
MIN_SERVER_VER_PNL: Final = 127
MIN_SERVER_VER_NEWS_QUERY_ORIGINS: Final = 128
MIN_SERVER_VER_UNREALIZED_PNL: Final = 129
MIN_SERVER_VER_HISTORICAL_TICKS: Final = 130
MIN_SERVER_VER_MARKET_CAP_PRICE: Final = 131
MIN_SERVER_VER_PRE_OPEN_BID_ASK: Final = 132
MIN_SERVER_VER_REAL_EXPIRATION_DATE: Final = 134
MIN_SERVER_VER_REALIZED_PNL: Final = 135
MIN_SERVER_VER_LAST_LIQUIDITY: Final = 136
MIN_SERVER_VER_TICK_BY_TICK: Final = 137
MIN_SERVER_VER_DECISION_MAKER: Final = 138
MIN_SERVER_VER_MIFID_EXECUTION: Final = 139
MIN_SERVER_VER_TICK_BY_TICK_IGNORE_SIZE: Final = 140
MIN_SERVER_VER_AUTO_PRICE_FOR_HEDGE: Final = 141
MIN_SERVER_VER_WHAT_IF_EXT_FIELDS: Final = 142
MIN_SERVER_VER_SCANNER_GENERIC_OPTS: Final = 143
MIN_SERVER_VER_API_BIND_ORDER: Final = 144
MIN_SERVER_VER_ORDER_CONTAINER: Final = 145
MIN_SERVER_VER_SMART_DEPTH: Final = 146
MIN_SERVER_VER_REMOVE_NULL_ALL_CASTING: Final = 147
MIN_SERVER_VER_D_PEG_ORDERS: Final = 148
MIN_SERVER_VER_MKT_DEPTH_PRIM_EXCHANGE: Final = 149
MIN_SERVER_VER_COMPLETED_ORDERS: Final = 150
MIN_SERVER_VER_PRICE_MGMT_ALGO: Final = 151
MIN_SERVER_VER_STOCK_TYPE: Final = 152
MIN_SERVER_VER_ENCODE_MSG_ASCII7: Final = 153
MIN_SERVER_VER_SEND_ALL_FAMILY_CODES: Final = 154
MIN_SERVER_VER_NO_DEFAULT_OPEN_CLOSE: Final = 155
MIN_SERVER_VER_PRICE_BASED_VOLATILITY: Final = 156
MIN_SERVER_VER_REPLACE_FA_END: Final = 157
MIN_SERVER_VER_DURATION: Final = 158
MIN_SERVER_VER_MARKET_DATA_IN_SHARES: Final = 159
MIN_SERVER_VER_POST_TO_ATS: Final = 160
MIN_SERVER_VER_WSHE_CALENDAR: Final = 161
MIN_SERVER_VER_AUTO_CANCEL_PARENT: Final = 162
MIN_SERVER_VER_FRACTIONAL_SIZE_SUPPORT: Final = 163
MIN_SERVER_VER_SIZE_RULES: Final = 164
MIN_SERVER_VER_HISTORICAL_SCHEDULE: Final = 165
MIN_SERVER_VER_ADVANCED_ORDER_REJECT: Final = 166
MIN_SERVER_VER_USER_INFO: Final = 167
MIN_SERVER_VER_CRYPTO_AGGREGATED_TRADES: Final = 168
MIN_SERVER_VER_MANUAL_ORDER_TIME: Final = 169
MIN_SERVER_VER_PEGBEST_PEGMID_OFFSETS: Final = 170
MIN_SERVER_VER_WSH_EVENT_DATA_FILTERS: Final = 171
MIN_SERVER_VER_IPO_PRICES: Final = 172
MIN_SERVER_VER_WSH_EVENT_DATA_FILTERS_DATE: Final = 173
MIN_SERVER_VER_INSTRUMENT_TIMEZONE: Final = 174
MIN_SERVER_VER_HMDS_MARKET_DATA_IN_SHARES: Final = 175
MIN_SERVER_VER_BOND_ISSUERID: Final = 176
MIN_SERVER_VER_FA_PROFILE_DESUPPORT: Final = 177
MIN_SERVER_VER_PENDING_PRICE_REVISION: Final = 178
MIN_SERVER_VER_FUND_DATA_FIELDS: Final = 179
MIN_SERVER_VER_MANUAL_ORDER_TIME_EXERCISE_OPTIONS: Final = 180
MIN_SERVER_VER_OPEN_ORDER_AD_STRATEGY: Final = 181
MIN_SERVER_VER_LAST_TRADE_DATE: Final = 182
MIN_SERVER_VER_CUSTOMER_ACCOUNT: Final = 183
MIN_SERVER_VER_PROFESSIONAL_CUSTOMER: Final = 184
MIN_SERVER_VER_BOND_ACCRUED_INTEREST: Final = 185
MIN_SERVER_VER_INELIGIBILITY_REASONS: Final = 186
MIN_SERVER_VER_RFQ_FIELDS: Final = 187
MIN_SERVER_VER_BOND_TRADING_HOURS: Final = 188
MIN_SERVER_VER_INCLUDE_OVERNIGHT: Final = 189
MIN_SERVER_VER_UNDO_RFQ_FIELDS: Final = 190
MIN_SERVER_VER_PERM_ID_AS_LONG: Final = 191
MIN_SERVER_VER_CME_TAGGING_FIELDS: Final = 192
MIN_SERVER_VER_CME_TAGGING_FIELDS_IN_OPEN_ORDER: Final = 193
MIN_SERVER_VER_ERROR_TIME: Final = 194
MIN_SERVER_VER_FULL_ORDER_PREVIEW_FIELDS: Final = 195
MIN_SERVER_VER_HISTORICAL_DATA_END: Final = 196
MIN_SERVER_VER_CURRENT_TIME_IN_MILLIS: Final = 197
MIN_SERVER_VER_SUBMITTER: Final = 198
MIN_SERVER_VER_IMBALANCE_ONLY: Final = 199
MIN_SERVER_VER_PARAMETRIZED_DAYS_OF_EXECUTIONS: Final = 200
MIN_SERVER_VER_PROTOBUF: Final = 201
MIN_SERVER_VER_ZERO_STRIKE: Final = 202
MIN_SERVER_VER_PROTOBUF_PLACE_ORDER: Final = 203
MIN_SERVER_VER_PROTOBUF_COMPLETED_ORDER: Final = 204
MIN_SERVER_VER_PROTOBUF_CONTRACT_DATA: Final = 205
MIN_SERVER_VER_PROTOBUF_MARKET_DATA: Final = 206
MIN_SERVER_VER_PROTOBUF_ACCOUNTS_POSITIONS: Final = 207
MIN_SERVER_VER_PROTOBUF_HISTORICAL_DATA: Final = 208
MIN_SERVER_VER_PROTOBUF_NEWS_DATA: Final = 209
MIN_SERVER_VER_PROTOBUF_SCAN_DATA: Final = 210
MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_1: Final = 211
MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_2: Final = 212
MIN_SERVER_VER_PROTOBUF_REST_MESSAGES_3: Final = 213
MIN_SERVER_VER_ADD_Z_SUFFIX_TO_UTC_DATE_TIME: Final = 214
MIN_SERVER_VER_CANCEL_CONTRACT_DATA: Final = 215
MIN_SERVER_VER_ADDITIONAL_ORDER_PARAMS_1: Final = 216
MIN_SERVER_VER_ADDITIONAL_ORDER_PARAMS_2: Final = 217
MIN_SERVER_VER_ATTACHED_ORDERS: Final = 218
MIN_SERVER_VER_CONFIG: Final = 219
MIN_SERVER_VER_MARKET_DATA_VOLUMES_IN_SHARES: Final = 220
MIN_SERVER_VER_UPDATE_CONFIG: Final = 221
MIN_SERVER_VER_FRACTIONAL_LAST_SIZE: Final = 222
MIN_SERVER_VER_HEDGE_MAX_SIZE: Final = 223
MIN_SERVER_VER_USE_PRECISION_FROM_SEC_DEF: Final = 224
MIN_SERVER_VER_ODD_LOT_BID_ASK_QUOTES: Final = 225

# --- Client-side handshake bounds
# MIN_CLIENT_VER below 100 used the pre-enhanced-handshake path (no length
# prefix on the wire). We don't support that ancient framing.
MIN_CLIENT_VER: Final = 100
# MAX_CLIENT_VER tracks the latest IBKR feature gate the codebase has
# audited and patched for. Bumping this ALSO requires patches to every
# conditional read/write at the new gate — see ``client.py`` and
# ``decoder.py``. Do not bump without sequencing those fixes.
MAX_CLIENT_VER: Final = MIN_SERVER_VER_ODD_LOT_BID_ASK_QUOTES
