name: ib_async

on: [push, pull_request]

jobs:
  build-poetry:
    name: poetry (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14", "pypy3.11"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry toolchain
        run: |
          pip install pip poetry setuptools wheel -U

      - name: Install dependencies with Poetry
        run: |
          poetry install --with=dev

      - name: MyPy static code analysis
        if: ${{ !startsWith(matrix.python-version, 'pypy') }}
        run: |
          poetry run mypy --pretty ib_async

      - name: Ruff check
        run: |
          poetry run ruff check

  build-uv:
    name: uv (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14", "pypy3.11"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv toolchain
        run: |
          pip install pip uv setuptools wheel -U

      - name: Install dependencies with uv
        run: |
          uv sync --group dev

      - name: MyPy static code analysis
        if: ${{ !startsWith(matrix.python-version, 'pypy') }}
        run: |
          uv run mypy --pretty ib_async

      - name: Ruff check
        run: |
          uv run ruff check
